# Dumb Charades — English films.
#
# Tuple: (title, category)
#
# Same contract as charades_hindi.py: no drawability axes, no fun gate, because
# neither describes what makes a film title good to act. What is enforced is
# recognition — a title nobody in the room has heard of is a dead round, not a
# hard one — and a word count a person can hold up on one hand.
#
# `category` drives anti-clustering only. Era for the pre-1970 shelf, genre
# after that.
#
# Full stops stay out of the middle of words: word_count() splits on
# non-alphanumerics, so "Dr. Strangelove" would signal two words and "E.T." four.
# Titles are written the way they can be counted honestly.
#
# Apostrophes DO belong, and are written: word_count() closes them up, and so
# does film_norm(), so "Schindler's List" counts two words and keys to the same
# ordinal it would without the apostrophe. A title printed in front of a room
# should be spelled the way the room spells it.

WORDS = [

    # --- the old canon ---
    ("Casablanca", "classic"),
    ("Gone with the Wind", "classic"),
    ("Citizen Kane", "classic"),
    ("The Wizard of Oz", "classic"),
    ("Singin’ in the Rain", "classic"),
    ("Psycho", "classic"),
    ("Vertigo", "classic"),
    ("Rear Window", "classic"),
    ("North by Northwest", "classic"),
    ("Some Like It Hot", "classic"),
    ("12 Angry Men", "classic"),
    ("Ben-Hur", "classic"),
    ("Lawrence of Arabia", "classic"),
    ("The Sound of Music", "classic"),
    ("Breakfast at Tiffany’s", "classic"),
    ("To Kill a Mockingbird", "classic"),
    ("Sunset Boulevard", "classic"),
    ("It’s a Wonderful Life", "classic"),
    ("The Great Escape", "classic"),
    ("Dr Strangelove", "classic"),
    ("Bonnie and Clyde", "classic"),
    ("The Bridge on the River Kwai", "classic"),
    ("Roman Holiday", "classic"),
    ("King Kong", "classic"),
    ("Metropolis", "classic"),
    ("Modern Times", "classic"),
    ("The Gold Rush", "classic"),
    ("City Lights", "classic"),
    ("Rebel Without a Cause", "classic"),
    ("On the Waterfront", "classic"),
    ("A Streetcar Named Desire", "classic"),
    ("The Third Man", "classic"),
    ("Double Indemnity", "classic"),
    ("The Maltese Falcon", "classic"),
    ("Mary Poppins", "classic"),
    ("My Fair Lady", "classic"),
    ("West Side Story", "classic"),
    ("The Birds", "classic"),
    ("Cleopatra", "classic"),
    ("The Seven Year Itch", "classic"),

    # --- drama ---
    ("The Godfather", "drama"),
    ("The Shawshank Redemption", "drama"),
    ("Forrest Gump", "drama"),
    ("Schindler’s List", "drama"),
    ("One Flew Over the Cuckoos Nest", "drama"),
    ("American Beauty", "drama"),
    ("Fight Club", "drama"),
    ("The Green Mile", "drama"),
    ("Good Will Hunting", "drama"),
    ("A Beautiful Mind", "drama"),
    ("The Pursuit of Happyness", "drama"),
    ("Dead Poets Society", "drama"),
    ("Rain Man", "drama"),
    ("Million Dollar Baby", "drama"),
    ("The Social Network", "drama"),
    ("The Wolf of Wall Street", "drama"),
    ("There Will Be Blood", "drama"),
    ("No Country for Old Men", "drama"),
    ("Moonlight", "drama"),
    ("Manchester by the Sea", "drama"),
    ("Whiplash", "drama"),
    ("Nomadland", "drama"),
    ("Marriage Story", "drama"),
    ("Little Women", "drama"),
    ("Everything Everywhere All at Once", "drama"),
    ("Oppenheimer", "drama"),
    ("Past Lives", "drama"),
    ("The Holdovers", "drama"),
    ("Room", "drama"),
    ("Spotlight", "drama"),
    ("Birdman", "drama"),
    ("Boyhood", "drama"),
    ("Her", "drama"),
    ("Lost in Translation", "drama"),
    ("Big Fish", "drama"),
    ("Cast Away", "drama"),
    ("The Truman Show", "drama"),
    ("Erin Brockovich", "drama"),
    ("Philadelphia", "drama"),
    ("The Elephant Man", "drama"),

    # --- action ---
    ("Die Hard", "action"),
    ("The Terminator", "action"),
    ("Terminator 2 Judgment Day", "action"),
    ("Mad Max Fury Road", "action"),
    ("John Wick", "action"),
    ("Mission Impossible", "action"),
    ("Top Gun", "action"),
    ("Top Gun Maverick", "action"),
    ("Speed", "action"),
    ("The Bourne Identity", "action"),
    ("Casino Royale", "action"),
    ("Skyfall", "action"),
    ("Goldfinger", "action"),
    ("Rambo", "action"),
    ("Predator", "action"),
    ("Face Off", "action"),
    ("The Rock", "action"),
    ("Con Air", "action"),
    ("Bad Boys", "action"),
    ("Lethal Weapon", "action"),
    ("Heat", "action"),
    ("The Dark Knight", "action"),
    ("Gladiator", "action"),
    ("300", "action"),
    ("Kill Bill", "action"),
    ("The Matrix", "action"),
    ("Rush Hour", "action"),
    ("Ocean’s Eleven", "action"),
    ("The Italian Job", "action"),
    ("Taken", "action"),
    ("The Fast and the Furious", "action"),
    ("Baby Driver", "action"),
    ("Atomic Blonde", "action"),
    ("Sicario", "action"),
    ("The Bourne Ultimatum", "action"),

    # --- science fiction ---
    ("2001 A Space Odyssey", "scifi"),
    ("Blade Runner", "scifi"),
    ("Blade Runner 2049", "scifi"),
    ("Star Wars", "scifi"),
    ("The Empire Strikes Back", "scifi"),
    ("Return of the Jedi", "scifi"),
    ("Inception", "scifi"),
    ("Interstellar", "scifi"),
    ("Arrival", "scifi"),
    ("The Martian", "scifi"),
    ("Gravity", "scifi"),
    ("Ex Machina", "scifi"),
    ("Dune", "scifi"),
    ("Avatar", "scifi"),
    ("District 9", "scifi"),
    ("Minority Report", "scifi"),
    ("Total Recall", "scifi"),
    ("Jurassic Park", "scifi"),
    ("Alien", "scifi"),
    ("Aliens", "scifi"),
    ("Back to the Future", "scifi"),
    ("Close Encounters of the Third Kind", "scifi"),
    ("ET the Extra-Terrestrial", "scifi"),
    ("Contact", "scifi"),
    ("Looper", "scifi"),
    ("Edge of Tomorrow", "scifi"),
    ("Children of Men", "scifi"),
    ("Snowpiercer", "scifi"),
    ("Annihilation", "scifi"),
    ("Tenet", "scifi"),
    ("The Fifth Element", "scifi"),
    ("I Robot", "scifi"),
    ("War of the Worlds", "scifi"),
    ("Independence Day", "scifi"),
    ("Men in Black", "scifi"),

    # --- comedy ---
    ("Groundhog Day", "comedy"),
    ("The Hangover", "comedy"),
    ("Superbad", "comedy"),
    ("Bridesmaids", "comedy"),
    ("Anchorman", "comedy"),
    ("Dumb and Dumber", "comedy"),
    ("Home Alone", "comedy"),
    ("Mrs Doubtfire", "comedy"),
    ("Ghostbusters", "comedy"),
    ("Airplane", "comedy"),
    ("The Big Lebowski", "comedy"),
    ("Napoleon Dynamite", "comedy"),
    ("School of Rock", "comedy"),
    ("Meet the Parents", "comedy"),
    ("Zoolander", "comedy"),
    ("Borat", "comedy"),
    ("Shaun of the Dead", "comedy"),
    ("Hot Fuzz", "comedy"),
    ("The Grand Budapest Hotel", "comedy"),
    ("Little Miss Sunshine", "comedy"),
    ("Juno", "comedy"),
    ("Knives Out", "comedy"),
    ("Game Night", "comedy"),
    ("The Nice Guys", "comedy"),
    ("Tropic Thunder", "comedy"),
    ("21 Jump Street", "comedy"),
    ("Pitch Perfect", "comedy"),
    ("Legally Blonde", "comedy"),
    ("Mean Girls", "comedy"),
    ("Clueless", "comedy"),
    ("The Devil Wears Prada", "comedy"),
    ("Crazy Rich Asians", "comedy"),
    ("Booksmart", "comedy"),
    ("Barbie", "comedy"),
    ("Jojo Rabbit", "comedy"),
    ("Office Space", "comedy"),
    ("Wedding Crashers", "comedy"),
    ("Step Brothers", "comedy"),

    # --- romance ---
    ("Titanic", "romance"),
    ("La La Land", "romance"),
    ("Notting Hill", "romance"),
    ("Four Weddings and a Funeral", "romance"),
    ("Love Actually", "romance"),
    ("When Harry Met Sally", "romance"),
    ("Sleepless in Seattle", "romance"),
    ("Pretty Woman", "romance"),
    ("The Notebook", "romance"),
    ("Before Sunrise", "romance"),
    ("Before Sunset", "romance"),
    ("Eternal Sunshine of the Spotless Mind", "romance"),
    ("Silver Linings Playbook", "romance"),
    ("About Time", "romance"),
    ("500 Days of Summer", "romance"),
    ("Call Me by Your Name", "romance"),
    ("The Fault in Our Stars", "romance"),
    ("A Star Is Born", "romance"),
    ("Brokeback Mountain", "romance"),
    ("Ghost", "romance"),
    ("Dirty Dancing", "romance"),
    ("Moulin Rouge", "romance"),
    ("The Great Gatsby", "romance"),
    ("Atonement", "romance"),
    ("Pride and Prejudice", "romance"),
    ("Sense and Sensibility", "romance"),
    ("The Bridges of Madison County", "romance"),
    ("Me Before You", "romance"),

    # --- thriller ---
    ("The Silence of the Lambs", "thriller"),
    ("Se7en", "thriller"),
    ("Zodiac", "thriller"),
    ("Gone Girl", "thriller"),
    ("Shutter Island", "thriller"),
    ("Memento", "thriller"),
    ("Prisoners", "thriller"),
    ("The Sixth Sense", "thriller"),
    ("The Usual Suspects", "thriller"),
    ("Nightcrawler", "thriller"),
    ("Parasite", "thriller"),
    ("Oldboy", "thriller"),
    ("The Girl with the Dragon Tattoo", "thriller"),
    ("Panic Room", "thriller"),
    ("Split", "thriller"),
    ("Get Out", "thriller"),
    ("Us", "thriller"),
    ("A Quiet Place", "thriller"),
    ("The Prestige", "thriller"),
    ("Black Swan", "thriller"),
    ("Fargo", "thriller"),
    ("The Departed", "thriller"),
    ("Wind River", "thriller"),
    ("Searching", "thriller"),
    ("Jaws", "thriller"),

    # --- crime ---
    ("Goodfellas", "crime"),
    ("Pulp Fiction", "crime"),
    ("Scarface", "crime"),
    ("Casino", "crime"),
    ("The Untouchables", "crime"),
    ("Reservoir Dogs", "crime"),
    ("American Gangster", "crime"),
    ("Catch Me If You Can", "crime"),
    ("The Irishman", "crime"),
    ("Snatch", "crime"),
    ("Lock Stock and Two Smoking Barrels", "crime"),
    ("City of God", "crime"),
    ("Training Day", "crime"),
    ("LA Confidential", "crime"),
    ("Public Enemies", "crime"),
    ("The Town", "crime"),
    ("Widows", "crime"),
    ("Inside Man", "crime"),
    ("Now You See Me", "crime"),
    ("The Godfather Part II", "crime"),

    # --- horror ---
    ("The Exorcist", "horror"),
    ("The Shining", "horror"),
    ("Halloween", "horror"),
    ("A Nightmare on Elm Street", "horror"),
    ("Scream", "horror"),
    ("It", "horror"),
    ("The Conjuring", "horror"),
    ("Insidious", "horror"),
    ("Hereditary", "horror"),
    ("The Babadook", "horror"),
    ("The Ring", "horror"),
    ("Sinister", "horror"),
    ("Paranormal Activity", "horror"),
    ("The Witch", "horror"),
    ("Midsommar", "horror"),
    ("The Blair Witch Project", "horror"),
    ("Poltergeist", "horror"),
    ("Carrie", "horror"),
    ("The Thing", "horror"),
    ("Nosferatu", "horror"),
    ("Dracula", "horror"),
    ("Frankenstein", "horror"),
    ("Annabelle", "horror"),
    ("Saw", "horror"),
    ("Final Destination", "horror"),
    ("28 Days Later", "horror"),

    # --- animation ---
    ("Toy Story", "animation"),
    ("Finding Nemo", "animation"),
    ("The Lion King", "animation"),
    ("Up", "animation"),
    ("Inside Out", "animation"),
    ("Coco", "animation"),
    ("Ratatouille", "animation"),
    ("Monsters Inc", "animation"),
    ("WALL-E", "animation"),
    ("Shrek", "animation"),
    ("Frozen", "animation"),
    ("Moana", "animation"),
    ("Zootopia", "animation"),
    ("Kung Fu Panda", "animation"),
    ("How to Train Your Dragon", "animation"),
    ("Despicable Me", "animation"),
    ("Spirited Away", "animation"),
    ("My Neighbour Totoro", "animation"),
    ("Spider-Man Into the Spider-Verse", "animation"),
    ("The Incredibles", "animation"),
    ("Big Hero 6", "animation"),
    ("Encanto", "animation"),
    ("Soul", "animation"),
    ("Turning Red", "animation"),
    ("Luca", "animation"),
    ("Brave", "animation"),
    ("Tangled", "animation"),
    ("Aladdin", "animation"),
    ("Beauty and the Beast", "animation"),
    ("Cinderella", "animation"),
    ("Snow White and the Seven Dwarfs", "animation"),
    ("Pinocchio", "animation"),
    ("Bambi", "animation"),
    ("Dumbo", "animation"),
    ("The Jungle Book", "animation"),
    ("Toy Story 3", "animation"),
    ("Ice Age", "animation"),
    ("Madagascar", "animation"),

    # --- fantasy ---
    ("The Lord of the Rings", "fantasy"),
    ("The Two Towers", "fantasy"),
    ("The Return of the King", "fantasy"),
    ("The Hobbit", "fantasy"),
    ("Harry Potter and the Philosophers Stone", "fantasy"),
    ("Harry Potter and the Prisoner of Azkaban", "fantasy"),
    ("The Chronicles of Narnia", "fantasy"),
    ("Pans Labyrinth", "fantasy"),
    ("The Shape of Water", "fantasy"),
    ("Edward Scissorhands", "fantasy"),
    ("Big", "fantasy"),
    ("The NeverEnding Story", "fantasy"),
    ("Willy Wonka and the Chocolate Factory", "fantasy"),
    ("Alice in Wonderland", "fantasy"),
    ("Stardust", "fantasy"),
    ("The Princess Bride", "fantasy"),
    ("Hook", "fantasy"),
    ("Beetlejuice", "fantasy"),

    # --- adventure ---
    ("Raiders of the Lost Ark", "adventure"),
    ("Indiana Jones and the Last Crusade", "adventure"),
    ("Jurassic World", "adventure"),
    ("Pirates of the Caribbean", "adventure"),
    ("The Mummy", "adventure"),
    ("National Treasure", "adventure"),
    ("Life of Pi", "adventure"),
    ("Into the Wild", "adventure"),
    ("The Secret Life of Walter Mitty", "adventure"),
    ("Jumanji", "adventure"),
    ("The Goonies", "adventure"),
    ("Around the World in 80 Days", "adventure"),
    ("The Revenant", "adventure"),
    ("Slumdog Millionaire", "adventure"),
    ("The Beach", "adventure"),

    # --- war ---
    ("Saving Private Ryan", "war"),
    ("Apocalypse Now", "war"),
    ("Full Metal Jacket", "war"),
    ("Platoon", "war"),
    ("Dunkirk", "war"),
    ("1917", "war"),
    ("Hacksaw Ridge", "war"),
    ("Black Hawk Down", "war"),
    ("The Hurt Locker", "war"),
    ("Inglourious Basterds", "war"),
    ("The Pianist", "war"),
    ("Life Is Beautiful", "war"),
    ("The Thin Red Line", "war"),
    ("Letters from Iwo Jima", "war"),
    ("Fury", "war"),
    ("American Sniper", "war"),
    ("Master and Commander", "war"),

    # --- sport ---
    ("Rocky", "sports"),
    ("Raging Bull", "sports"),
    ("Moneyball", "sports"),
    ("The Blind Side", "sports"),
    ("Remember the Titans", "sports"),
    ("Coach Carter", "sports"),
    ("Creed", "sports"),
    ("Ford v Ferrari", "sports"),
    ("Rush", "sports"),
    ("The Fighter", "sports"),
    ("Invictus", "sports"),
    ("Miracle", "sports"),
    ("Field of Dreams", "sports"),
    ("Chariots of Fire", "sports"),
    ("Space Jam", "sports"),
    ("Bend It Like Beckham", "sports"),
    ("Cool Runnings", "sports"),

    # --- music and the stage ---
    ("The Greatest Showman", "musical"),
    ("Chicago", "musical"),
    ("Grease", "musical"),
    ("Hairspray", "musical"),
    ("Les Miserables", "musical"),
    ("Mamma Mia", "musical"),
    ("The Phantom of the Opera", "musical"),
    ("Rocketman", "musical"),
    ("Bohemian Rhapsody", "musical"),
    ("Walk the Line", "musical"),
    ("Almost Famous", "musical"),
    ("A Hard Days Night", "musical"),
    ("Across the Universe", "musical"),
    ("Sing Street", "musical"),
    ("The Blues Brothers", "musical"),
    ("Dreamgirls", "musical"),

    # --- capes ---
    ("The Avengers", "superhero"),
    ("Avengers Endgame", "superhero"),
    ("Avengers Infinity War", "superhero"),
    ("Iron Man", "superhero"),
    ("Captain America The Winter Soldier", "superhero"),
    ("Black Panther", "superhero"),
    ("Thor Ragnarok", "superhero"),
    ("Guardians of the Galaxy", "superhero"),
    ("Doctor Strange", "superhero"),
    ("Spider-Man", "superhero"),
    ("Spider-Man No Way Home", "superhero"),
    ("The Dark Knight Rises", "superhero"),
    ("Batman Begins", "superhero"),
    ("Wonder Woman", "superhero"),
    ("Man of Steel", "superhero"),
    ("Deadpool", "superhero"),
    ("Logan", "superhero"),
    ("X-Men", "superhero"),
    ("Joker", "superhero"),
    ("Shazam", "superhero"),
    ("Aquaman", "superhero"),
    ("Superman", "superhero"),
]
