# Dumb Charades — Hindi films.
#
# Tuple: (title, category)
#
# There are no drawability axes here. Difficulty in charades is not the same
# problem as difficulty in Pictionary — a film title is acted, not drawn — so the
# four-axis rubric in scripts/build_corpus.py does not apply and is not run
# against these. The gates that survive are the ones a party actually notices:
# the title has to be one a room will recognise, and short enough to signal on
# fingers.
#
# `category` exists for anti-clustering, so consecutive titles do not all come
# off the same shelf. Era for the older half, genre for the rest — that is the
# grouping a room feels.
#
# Punctuation stays out of the middle of words. word_count() splits on
# non-alphanumerics, so "Munna Bhai M.B.B.S." would signal six words instead of
# three and the pips would lie to the people guessing.

WORDS = [

    # --- golden age and pre-1980 ---
    ("Mother India", "classic"),
    ("Mughal-e-Azam", "classic"),
    ("Sholay", "classic"),
    ("Pyaasa", "classic"),
    ("Guide", "classic"),
    ("Awaara", "classic"),
    ("Shree 420", "classic"),
    ("Do Bigha Zamin", "classic"),
    ("Kaagaz Ke Phool", "classic"),
    ("Anand", "classic"),
    ("Deewaar", "classic"),
    ("Zanjeer", "classic"),
    ("Amar Akbar Anthony", "classic"),
    ("Bobby", "classic"),
    ("Aradhana", "classic"),
    ("Sahib Bibi Aur Ghulam", "classic"),
    ("Padosan", "classic"),
    ("Jewel Thief", "classic"),
    ("Teesri Manzil", "classic"),
    ("Waqt", "classic"),
    ("Haathi Mere Saathi", "classic"),
    ("Upkar", "classic"),
    ("Barsaat", "classic"),
    ("Madhumati", "classic"),
    ("Pakeezah", "classic"),
    ("Umrao Jaan", "classic"),
    ("Namak Haraam", "classic"),
    ("Abhimaan", "classic"),
    ("Bawarchi", "classic"),
    ("Chalti Ka Naam Gaadi", "classic"),
    ("Kabhi Kabhie", "classic"),
    ("Trishul", "classic"),
    ("Don", "classic"),
    ("Muqaddar Ka Sikandar", "classic"),
    ("Kaala Patthar", "classic"),
    ("Satyam Shivam Sundaram", "classic"),
    ("Naya Daur", "classic"),
    ("Mera Naam Joker", "classic"),
    ("Sangam", "classic"),
    ("Seeta Aur Geeta", "classic"),
    ("Bombay to Goa", "classic"),
    ("Yaadon Ki Baaraat", "classic"),
    ("Roti Kapda Aur Makaan", "classic"),
    ("Chhoti Si Baat", "classic"),
    ("Golmaal", "classic"),
    ("Chupke Chupke", "classic"),
    ("Khubsoorat", "classic"),
    ("Bandini", "classic"),
    ("Kismet", "classic"),
    ("Howrah Bridge", "classic"),
    ("Chaudhvin Ka Chand", "classic"),
    ("Mere Mehboob", "classic"),
    ("Aar Paar", "classic"),
    ("Boot Polish", "classic"),
    ("Jagte Raho", "classic"),
    ("Baton Baton Mein", "classic"),
    ("Amrapali", "classic"),
    ("Junoon", "classic"),
    ("Sparsh", "classic"),
    ("Garam Hawa", "classic"),
    ("Chashme Buddoor", "classic"),
    ("Arth", "classic"),

    # --- eighties and nineties mainstream ---
    ("Mr India", "masala"),
    ("Tezaab", "masala"),
    ("Qayamat Se Qayamat Tak", "masala"),
    ("Maine Pyar Kiya", "masala"),
    ("Chandni", "masala"),
    ("Ram Lakhan", "masala"),
    ("Tridev", "masala"),
    ("Baazigar", "masala"),
    ("Darr", "masala"),
    ("Karan Arjun", "masala"),
    ("Khalnayak", "masala"),
    ("Saajan", "masala"),
    ("Beta", "masala"),
    ("Raja Hindustani", "masala"),
    ("Judwaa", "masala"),
    ("Coolie No 1", "masala"),
    ("Biwi No 1", "masala"),
    ("Hero No 1", "masala"),
    ("Rangeela", "masala"),
    ("Gupt", "masala"),
    ("Ghayal", "masala"),
    ("Damini", "masala"),
    ("Anari", "masala"),
    ("Hum", "masala"),
    ("Khuda Gawah", "masala"),
    ("Mohra", "masala"),
    ("Krantiveer", "masala"),
    ("Chaalbaaz", "masala"),
    ("Lamhe", "masala"),
    ("Saudagar", "masala"),
    ("Hum Aapke Hain Koun", "masala"),
    ("Dilwale Dulhania Le Jayenge", "masala"),
    ("Kuch Kuch Hota Hai", "masala"),
    ("Pardes", "masala"),
    ("Dil To Pagal Hai", "masala"),
    ("Yes Boss", "masala"),
    ("Duplicate", "masala"),
    ("Deewana", "masala"),
    ("Kabhi Haan Kabhi Naa", "masala"),
    ("Jo Jeeta Wohi Sikandar", "masala"),
    ("Hum Hain Rahi Pyar Ke", "masala"),
    ("Akele Hum Akele Tum", "masala"),
    ("Dil", "masala"),
    ("Yaraana", "masala"),
    ("Ijaazat", "masala"),
    ("Parinda", "masala"),
    ("Ardh Satya", "masala"),
    ("Masoom", "masala"),
    ("Salaam Bombay", "masala"),
    ("Andaz Apna Apna", "masala"),

    # --- romance ---
    ("Veer-Zaara", "romance"),
    ("Kal Ho Naa Ho", "romance"),
    ("Kabhi Alvida Naa Kehna", "romance"),
    ("Jab We Met", "romance"),
    ("Rab Ne Bana Di Jodi", "romance"),
    ("Ae Dil Hai Mushkil", "romance"),
    ("Yeh Jawaani Hai Deewani", "romance"),
    ("Barfi", "romance"),
    ("Aashiqui 2", "romance"),
    ("Tamasha", "romance"),
    ("Rockstar", "romance"),
    ("Jab Tak Hai Jaan", "romance"),
    ("Hum Tum", "romance"),
    ("Salaam Namaste", "romance"),
    ("Socha Na Tha", "romance"),
    ("Band Baaja Baaraat", "romance"),
    ("Ishaqzaade", "romance"),
    ("Raanjhanaa", "romance"),
    ("Humpty Sharma Ki Dulhania", "romance"),
    ("2 States", "romance"),
    ("Shuddh Desi Romance", "romance"),
    ("Love Aaj Kal", "romance"),
    ("Cocktail", "romance"),
    ("Ek Ladki Ko Dekha Toh Aisa Laga", "romance"),
    ("Mohabbatein", "romance"),
    ("Devdas", "romance"),
    ("Saathiya", "romance"),
    ("Fanaa", "romance"),
    ("Aashiqui", "romance"),
    ("Dil Se", "romance"),
    ("Bombay", "romance"),
    ("Kaho Naa Pyaar Hai", "romance"),
    ("Sanam Teri Kasam", "romance"),
    ("Kabir Singh", "romance"),
    ("Laila Majnu", "romance"),
    ("Chalte Chalte", "romance"),

    # --- comedy ---
    ("Jaane Bhi Do Yaaro", "comedy"),
    ("Hera Pheri", "comedy"),
    ("Phir Hera Pheri", "comedy"),
    ("Munna Bhai MBBS", "comedy"),
    ("Lage Raho Munna Bhai", "comedy"),
    ("3 Idiots", "comedy"),
    ("Golmaal Returns", "comedy"),
    ("Dhamaal", "comedy"),
    ("Welcome", "comedy"),
    ("Bhool Bhulaiyaa", "comedy"),
    ("Chup Chup Ke", "comedy"),
    ("Garam Masala", "comedy"),
    ("Malamaal Weekly", "comedy"),
    ("Khosla Ka Ghosla", "comedy"),
    ("Bheja Fry", "comedy"),
    ("Delhi Belly", "comedy"),
    ("Fukrey", "comedy"),
    ("Stree", "comedy"),
    ("Badhaai Ho", "comedy"),
    ("Bareilly Ki Barfi", "comedy"),
    ("Shubh Mangal Saavdhan", "comedy"),
    ("Dream Girl", "comedy"),
    ("Chhichhore", "comedy"),
    ("Luka Chuppi", "comedy"),
    ("Jolly LLB", "comedy"),
    ("Piku", "comedy"),
    ("English Vinglish", "comedy"),
    ("Queen", "comedy"),
    ("Bala", "comedy"),
    ("Vicky Donor", "comedy"),
    ("Dum Laga Ke Haisha", "comedy"),
    ("Total Dhamaal", "comedy"),
    ("Housefull", "comedy"),
    ("Partner", "comedy"),
    ("Singh Is Kinng", "comedy"),
    ("No Entry", "comedy"),
    ("Shaadi Ke Side Effects", "comedy"),

    # --- action ---
    ("Dhoom", "action"),
    ("Dhoom 2", "action"),
    ("Krrish", "action"),
    ("Ek Tha Tiger", "action"),
    ("Tiger Zinda Hai", "action"),
    ("War", "action"),
    ("Pathaan", "action"),
    ("Jawan", "action"),
    ("Bang Bang", "action"),
    ("Baaghi", "action"),
    ("Singham", "action"),
    ("Dabangg", "action"),
    ("Rowdy Rathore", "action"),
    ("Wanted", "action"),
    ("Ghajini", "action"),
    ("Kick", "action"),
    ("Sooryavanshi", "action"),
    ("Simmba", "action"),
    ("Commando", "action"),
    ("Force", "action"),
    ("Agneepath", "action"),
    ("Shootout at Lokhandwala", "action"),
    ("Race", "action"),
    ("Don 2", "action"),
    ("Bhola", "action"),
    ("Marjaavaan", "action"),
    ("Satyameva Jayate", "action"),
    ("Toofan", "action"),

    # --- thriller ---
    ("Kahaani", "thriller"),
    ("Drishyam", "thriller"),
    ("Talaash", "thriller"),
    ("Andhadhun", "thriller"),
    ("Badla", "thriller"),
    ("Special 26", "thriller"),
    ("Baby", "thriller"),
    ("A Wednesday", "thriller"),
    ("Ittefaq", "thriller"),
    ("Te3n", "thriller"),
    ("Ugly", "thriller"),
    ("NH10", "thriller"),
    ("Raat Akeli Hai", "thriller"),
    ("Talvar", "thriller"),
    ("Detective Byomkesh Bakshy", "thriller"),
    ("Aitraaz", "thriller"),
    ("Murder", "thriller"),
    ("Bluffmaster", "thriller"),
    ("Johnny Gaddaar", "thriller"),
    ("Kaun", "thriller"),
    ("Manorama Six Feet Under", "thriller"),
    ("Table No 21", "thriller"),
    ("Trapped", "thriller"),
    ("Article 15", "thriller"),
    ("Raazi", "thriller"),
    ("Vikram Vedha", "thriller"),
    ("Kaminey", "thriller"),
    ("Ek Hasina Thi", "thriller"),
    ("Wazir", "thriller"),
    ("Raid", "thriller"),

    # --- crime and the underworld ---
    ("Satya", "crime"),
    ("Company", "crime"),
    ("Vaastav", "crime"),
    ("Gangs of Wasseypur", "crime"),
    ("Once Upon a Time in Mumbaai", "crime"),
    ("Raees", "crime"),
    ("Shootout at Wadala", "crime"),
    ("D-Day", "crime"),
    ("Omkara", "crime"),
    ("Maqbool", "crime"),
    ("Haider", "crime"),
    ("Gulaal", "crime"),
    ("Black Friday", "crime"),
    ("Sonchiriya", "crime"),
    ("Paan Singh Tomar", "crime"),
    ("Ab Tak Chhappan", "crime"),
    ("Kaante", "crime"),
    ("Bandit Queen", "crime"),
    ("Mumbai Meri Jaan", "crime"),
    ("Bombay Velvet", "crime"),

    # --- drama ---
    ("Taare Zameen Par", "drama"),
    ("Rang De Basanti", "drama"),
    ("Swades", "drama"),
    ("Black", "drama"),
    ("Guru", "drama"),
    ("Zindagi Na Milegi Dobara", "drama"),
    ("Dil Chahta Hai", "drama"),
    ("Wake Up Sid", "drama"),
    ("Udaan", "drama"),
    ("Masaan", "drama"),
    ("The Lunchbox", "drama"),
    ("Court", "drama"),
    ("Newton", "drama"),
    ("Gully Boy", "drama"),
    ("Pink", "drama"),
    ("Thappad", "drama"),
    ("Pagglait", "drama"),
    ("Tumhari Sulu", "drama"),
    ("Hindi Medium", "drama"),
    ("Toilet Ek Prem Katha", "drama"),
    ("Padman", "drama"),
    ("Mimi", "drama"),
    ("October", "drama"),
    ("Kapoor and Sons", "drama"),
    ("Dear Zindagi", "drama"),
    ("Highway", "drama"),
    ("Lootera", "drama"),
    ("Ship of Theseus", "drama"),
    ("Peepli Live", "drama"),
    ("Iqbal", "drama"),
    ("Do Dooni Chaar", "drama"),
    ("Ankhon Dekhi", "drama"),
    ("Chhapaak", "drama"),
    ("Serious Men", "drama"),
    ("Zwigato", "drama"),

    # --- family and festival films ---
    ("Kabhi Khushi Kabhie Gham", "family"),
    ("Hum Saath Saath Hain", "family"),
    ("Vivah", "family"),
    ("Baghban", "family"),
    ("Ek Rishtaa", "family"),
    ("Kal Aaj Aur Kal", "family"),
    ("Prem Ratan Dhan Payo", "family"),
    ("Hum Dil De Chuke Sanam", "family"),
    ("Chori Chori Chupke Chupke", "family"),
    ("Bawaal", "family"),
    ("Badhaai Do", "family"),
    ("Shaadi Mein Zaroor Aana", "family"),
    ("Dostana", "family"),
    ("Student of the Year", "family"),
    ("Uunchai", "family"),
    ("Maine Pyar Kyun Kiya", "family"),

    # --- sport ---
    ("Lagaan", "sports"),
    ("Chak De India", "sports"),
    ("Dangal", "sports"),
    ("Sultan", "sports"),
    ("Bhaag Milkha Bhaag", "sports"),
    ("Mary Kom", "sports"),
    ("MS Dhoni The Untold Story", "sports"),
    ("Soorma", "sports"),
    ("Gold", "sports"),
    ("83", "sports"),
    ("Jersey", "sports"),
    ("Saina", "sports"),
    ("Panga", "sports"),
    ("Shabaash Mithu", "sports"),
    ("Budhia Singh Born to Run", "sports"),

    # --- lives, real and retold ---
    ("Sanju", "biopic"),
    ("Neerja", "biopic"),
    ("Shershaah", "biopic"),
    ("Manikarnika", "biopic"),
    ("Bajirao Mastani", "biopic"),
    ("Padmaavat", "biopic"),
    ("Jodhaa Akbar", "biopic"),
    ("The Legend of Bhagat Singh", "biopic"),
    ("Mangal Pandey", "biopic"),
    ("Gangubai Kathiawadi", "biopic"),
    ("Shakuntala Devi", "biopic"),
    ("Super 30", "biopic"),
    ("Rocketry", "biopic"),
    ("Thalaivii", "biopic"),
    ("Azhar", "biopic"),
    ("Dasvi", "biopic"),
    ("Sam Bahadur", "biopic"),
    ("Mission Raniganj", "biopic"),
    ("Srikanth", "biopic"),
    ("12th Fail", "biopic"),

    # --- war and the border ---
    ("Border", "war"),
    ("Lakshya", "war"),
    ("Uri The Surgical Strike", "war"),
    ("LOC Kargil", "war"),
    ("Haqeeqat", "war"),
    ("Airlift", "war"),
    ("Kesari", "war"),
    ("Tanhaji", "war"),
    ("Parmanu", "war"),
    ("The Ghazi Attack", "war"),
    ("Shaurya", "war"),
    ("Prahaar", "war"),
    ("Sarfarosh", "war"),
    ("Bhuj The Pride of India", "war"),

    # --- horror and the uncanny ---
    ("Raaz", "horror"),
    ("Bhoot", "horror"),
    ("1920", "horror"),
    ("Tumbbad", "horror"),
    ("Pari", "horror"),
    ("Bulbbul", "horror"),
    ("Ragini MMS", "horror"),
    ("Darna Mana Hai", "horror"),
    ("Mahal", "horror"),
    ("Veerana", "horror"),
    ("Purana Mandir", "horror"),
    ("Stree 2", "horror"),
    ("Roohi", "horror"),
    ("Shaitaan", "horror"),
    ("Munjya", "horror"),
    ("Bhediya", "horror"),

    # --- songs, dance and the stage ---
    ("Om Shanti Om", "musical"),
    ("Taal", "musical"),
    ("Rock On", "musical"),
    ("Rock On 2", "musical"),
    ("ABCD Any Body Can Dance", "musical"),
    ("Street Dancer", "musical"),
    ("Jagga Jasoos", "musical"),
    ("Baiju Bawra", "musical"),
    ("Amar Prem", "musical"),
    ("Delhi 6", "musical"),

    # --- science fiction and the fantastical ---
    ("PK", "scifi"),
    ("Robot", "scifi"),
    ("Brahmastra", "scifi"),
    ("Koi Mil Gaya", "scifi"),
    ("Krrish 3", "scifi"),
    ("Ra One", "scifi"),
    ("Love Story 2050", "scifi"),
    ("Cargo", "scifi"),
    ("Mr X", "scifi"),
    ("Bhavesh Joshi Superhero", "scifi"),

    # --- since 2015, and a room will still name them ---
    ("Bajrangi Bhaijaan", "modern"),
    ("Tanu Weds Manu", "modern"),
    ("Tanu Weds Manu Returns", "modern"),
    ("Kai Po Che", "modern"),
    ("Fan", "modern"),
    ("Dilwale", "modern"),
    ("Bharat", "modern"),
    ("Good Newwz", "modern"),
    ("Kedarnath", "modern"),
    ("Sonu Ke Titu Ki Sweety", "modern"),
    ("Ludo", "modern"),
    ("AK vs AK", "modern"),
    ("Gehraiyaan", "modern"),
    ("Jugjugg Jeeyo", "modern"),
    ("Rocky Aur Rani Kii Prem Kahaani", "modern"),
    ("Animal", "modern"),
    ("Laapataa Ladies", "modern"),
    ("An Action Hero", "modern"),
    ("Monica O My Darling", "modern"),
    ("Darlings", "modern"),
    ("Mission Mangal", "modern"),
    ("Chandu Champion", "modern"),
    ("Kill", "modern"),
    ("Maharaj", "modern"),
    ("Sui Dhaaga", "modern"),
    ("Bhoot Police", "modern"),
    ("Sardar Udham", "modern"),
    ("Jawaani Jaaneman", "modern"),
]
