# Tier: God Mode — score >= 8 AND a specialist domain AND a mandatory hint
# Specialist domains: biases, philosophy, science, biology, economics, internet, maths, literature
# Gate: T >= 2, hint required (build fails without one), 1-of-3 playtest gate before shipping.
# Tuple: (text, category, C, F, D, R, T, hint)

WORDS = [

    # --- biases ---
    ("Barnum effect","biases",1,1,2,2,4,"That horoscope describes literally everyone."),
    ("Dunning-Kruger effect","biases",1,1,2,2,4,"Too inexperienced to know how inexperienced you are."),
    ("anchoring bias","biases",1,1,2,2,4,"The first number you heard is still steering you."),
    ("availability heuristic","biases",1,1,2,2,4,"Easy to recall, so it feels common."),
    ("base rate fallacy","biases",1,1,2,2,4,"You ignored how rare the thing actually is."),
    ("bystander effect","biases",1,2,3,3,4,"A crowd watched. Nobody helped."),
    ("choice paralysis","biases",1,2,2,4,4,"Thirty options, so you picked none."),
    ("cognitive dissonance","biases",1,1,2,3,4,"Two beliefs. One head. They cannot both be right."),
    ("confirmation bias","biases",1,1,2,3,4,"You went looking, and found exactly what you expected."),
    ("curse of knowledge","biases",1,1,2,2,4,"You can't remember what it was like not to know."),
    ("decision fatigue","biases",1,2,2,4,4,"By evening, every choice is a bad one."),
    ("endowment effect","biases",1,1,2,2,4,"It's worth more the moment it becomes yours."),
    ("false consensus","biases",1,1,2,2,4,"Everyone thinks like me. They don't."),
    ("framing effect","biases",1,1,2,3,4,"Ninety percent fat free sells better than ten percent fat."),
    ("fundamental attribution error","biases",1,1,2,2,4,"They're late because they're careless. You're late because of traffic."),
    ("gambler's fallacy","biases",1,1,2,3,4,"It's landed heads five times, so tails is 'due'."),
    ("halo effect","biases",1,2,2,3,4,"They're attractive, so you assume they're clever too."),
    ("illusion of control","biases",1,1,2,3,4,"Pressing the button harder does nothing."),
    ("in-group bias","biases",1,1,2,3,4,"Ours is better because it is ours."),
    ("loss aversion","biases",1,1,2,3,4,"Losing ten hurts more than winning ten feels good."),
    ("moral licensing","biases",1,1,2,2,4,"I ate the salad, so I've earned the cake."),
    ("negativity bias","biases",1,1,2,3,4,"One bad review outweighs nine good ones."),
    ("normalcy bias","biases",1,1,2,2,4,"The alarm is going off. Everyone keeps eating."),
    ("observer effect","biases",1,1,2,3,4,"Watching it changed it."),
    ("optimism bias","biases",1,1,2,3,4,"Bad things happen to other people."),
    ("placebo effect","biases",1,2,2,4,4,"The sugar pill worked anyway."),
    ("planning fallacy","biases",1,1,2,3,4,"It always takes three times longer than you said."),
    ("recency bias","biases",1,1,2,3,4,"The last thing that happened weighs the most."),
    ("self-serving bias","biases",1,1,2,3,4,"Wins are skill. Losses are bad luck."),
    ("spotlight effect","biases",1,1,2,3,4,"Nobody noticed your haircut."),
    ("status quo bias","biases",1,1,2,3,4,"Change is worse simply because it is change."),
    ("sunk cost fallacy","biases",1,1,2,3,4,"You've already paid. That is the worst reason to continue."),
    ("survivorship bias","biases",1,1,2,2,4,"You only counted the planes that came back."),

    # --- biology ---
    ("DNA replication","biology",2,3,3,4,3,"The ladder unzips and copies itself."),
    ("REM sleep","biology",2,3,3,4,4,"Eyes darting. This is where dreams happen."),
    ("antibiotic resistance","biology",1,2,2,4,3,"The survivors breed, and the medicine stops working."),
    ("apoptosis","biology",1,1,2,1,4,"Cells that kill themselves on purpose."),
    ("cellular respiration","biology",1,2,2,3,3,"Turning food into usable energy."),
    ("circadian rhythm","biology",1,2,2,4,4,"The clock you carry whether you like it or not."),
    ("convergent evolution","biology",1,1,2,2,4,"Unrelated species, same solution."),
    ("ecological succession","biology",1,1,2,2,4,"Bare rock, then moss, then forest."),
    ("epigenetics","biology",1,1,2,2,4,"The environment flipping switches on your genes."),
    ("genetic drift","biology",1,1,2,2,4,"Change by pure chance, not fitness."),
    ("herd immunity","biology",1,2,2,5,4,"Enough are protected that the rest are too."),
    ("hibernation cycle","biology",2,3,3,4,3,"Shut down through the cold months."),
    ("homeostasis","biology",1,1,2,3,4,"The body's relentless thermostat."),
    ("imprinting","biology",2,3,3,3,4,"The first thing it sees becomes its mother."),
    ("keystone species","biology",1,2,2,2,4,"Remove it and the whole system collapses."),
    ("mitosis","biology",2,3,3,4,3,"One cell becomes two identical ones."),
    ("muscle atrophy","biology",2,3,3,4,3,"Unused, so it wastes away."),
    ("natural selection","biology",1,2,2,5,3,"The ones that fit, breed. The rest don't."),
    ("neuroplasticity","biology",1,1,2,3,4,"The brain rewiring itself."),
    ("parasitism","biology",2,3,3,4,4,"One benefits. The other pays."),
    ("phantom limb","biology",2,3,3,4,4,"It itches, and it isn't there."),
    ("pheromones","biology",1,1,2,3,4,"Chemical messages you never consciously smell."),
    ("synaptic pruning","biology",1,1,2,2,4,"The brain deleting connections it stopped using."),
    ("the immune response","biology",1,2,2,4,3,"An army that learns its enemy."),
    ("the placebo response","biology",1,1,2,4,4,"Believing it works is what made it work."),

    # --- economics ---
    ("Nash equilibrium","economics",1,1,2,2,4,"Nobody gains by changing strategy alone."),
    ("arbitrage","economics",1,1,2,3,4,"Buy cheap here, sell dear there, risk nothing."),
    ("barrier to entry","economics",2,3,3,4,3,"The wall keeping new competitors out."),
    ("black swan event","economics",2,3,3,3,4,"Unthinkable, until it happens."),
    ("compound growth","economics",1,2,2,4,4,"Slow, slow, slow, then suddenly enormous."),
    ("creative destruction","economics",1,2,2,2,4,"The new industry kills the old one. That's the point."),
    ("diminishing returns","economics",1,1,3,3,3,"Each extra unit buys you less than the last."),
    ("economies of scale","economics",1,2,2,4,3,"Bigger means cheaper per unit."),
    ("first mover advantage","economics",1,2,2,4,4,"Get there first and own the ground."),
    ("game theory","economics",1,1,2,4,4,"Maths for when the other side is also thinking."),
    ("inelastic demand","economics",1,1,2,2,4,"They'll buy it whatever you charge."),
    ("inflation spiral","economics",1,2,2,4,4,"Prices rise, wages chase, prices rise again."),
    ("market saturation","economics",1,2,2,4,4,"Everyone who wants one already has one."),
    ("moral hazard","economics",1,1,2,2,4,"Insured against the risk, so you take more of it."),
    ("network effect","economics",1,2,2,4,3,"Worth more because everyone else is on it."),
    ("opportunity cost","economics",1,1,2,3,4,"What you gave up by choosing this."),
    ("perverse incentive","economics",1,1,2,3,4,"You rewarded it, so they did more of it. Badly."),
    ("planned obsolescence","economics",2,3,3,4,4,"Designed to break just after the warranty."),
    ("price elasticity","economics",1,1,2,3,4,"How much demand flinches when price moves."),
    ("supply shock","economics",1,2,2,3,4,"The supply vanishes overnight, the price explodes."),
    ("the Veblen good","economics",1,1,2,1,4,"Expensive is the feature. Cheaper would sell less."),
    ("the free rider problem","economics",2,3,3,3,4,"Enjoys the benefit, pays none of the cost."),
    ("the invisible hand","economics",2,3,3,3,4,"Self-interest, somehow producing public good."),
    ("the paradox of thrift","economics",1,1,2,2,4,"Everyone saves. Everyone gets poorer."),
    ("the prisoner's dilemma","economics",2,3,3,3,4,"Both stay silent and both win. Neither trusts the other."),
    ("the race to the bottom","economics",2,3,3,3,4,"Everyone undercuts until nobody profits."),
    ("the tragedy of the commons","economics",2,3,3,3,4,"Shared field. Everyone grazes. Nothing left."),
    ("vertical integration","economics",1,2,2,3,3,"Own every step from raw material to shop floor."),
    ("zero sum game","economics",1,2,2,4,4,"For me to win, you must lose exactly that much."),

    # --- internet ---
    ("Betteridge's law","internet",1,1,2,1,4,"Any headline ending in a question mark: the answer is no."),
    ("Godwin's law","internet",1,1,2,2,4,"Argue long enough and someone mentions Hitler."),
    ("Moore's law","internet",1,2,2,4,4,"Chips double in power, roughly every two years."),
    ("Poe's law","internet",1,1,2,2,4,"Satire indistinguishable from sincerity."),
    ("algorithmic bias","internet",1,1,2,3,4,"The machine learned our prejudices and scaled them."),
    ("astroturfing","internet",1,1,2,2,4,"Fake grassroots. Paid for."),
    ("attention economy","internet",1,2,2,3,4,"Your eyes are the product being sold."),
    ("clickbait economy","internet",2,3,3,4,4,"Outrage pays better than accuracy."),
    ("dead internet theory","internet",1,1,2,2,4,"What if most of it is bots talking to bots?"),
    ("digital footprint","internet",2,3,3,4,4,"Everything you did, still there."),
    ("digital minimalism","internet",1,2,2,3,4,"Deliberately owning fewer apps, fewer feeds."),
    ("doomscrolling","internet",2,3,3,4,4,"Can't stop reading things that make you feel worse."),
    ("echo chamber","internet",2,3,3,4,3,"Everyone agrees, because you removed everyone who didn't."),
    ("feature creep","internet",1,2,2,4,4,"It kept growing until nobody could use it."),
    ("filter bubble","internet",2,3,3,3,4,"The algorithm only shows you what you already like."),
    ("network congestion","internet",2,3,3,4,3,"Everyone connected at once, so nobody gets through."),
    ("open source","internet",1,2,2,5,4,"Anyone can read it, change it, and give it back."),
    ("planned virality","internet",1,1,2,2,4,"Engineered to look spontaneous."),
    ("rubber duck debugging","internet",3,4,3,2,4,"Explain the problem to a toy and solve it yourself."),
    ("technical debt","internet",1,2,2,4,4,"Shortcuts today, paid back with interest later."),
    ("the Streisand effect","internet",1,2,3,2,4,"Suppressing it is what made everyone look."),
    ("the bus factor","internet",2,3,3,2,5,"How many people can leave before the project dies."),
    ("the long tail","internet",1,2,2,3,4,"A million niche things outselling the hits combined."),
    ("the uncanny valley","internet",2,3,3,3,4,"Almost human. That's what makes it horrifying."),

    # --- literature ---
    ("Chekhov's gun","literature",2,3,3,3,4,"If it's on the wall in act one, it fires by act three."),
    ("allegory","literature",1,1,2,3,4,"The whole story is secretly about something else."),
    ("bildungsroman","literature",1,1,2,1,4,"A story about growing up."),
    ("catharsis","literature",1,1,2,3,4,"The emotional release the ending gives you."),
    ("deus ex machina","literature",2,3,3,3,4,"A sudden rescue that solves everything. Cheating."),
    ("dramatic irony","literature",1,2,2,3,4,"The audience knows. The character doesn't."),
    ("epistolary","literature",2,3,3,1,4,"The whole novel told in letters."),
    ("foreshadowing","literature",1,2,2,4,4,"A hint of what's coming, planted early."),
    ("hyperbole","literature",1,2,2,4,4,"Absurd exaggeration, for effect."),
    ("in medias res","literature",1,1,2,2,4,"The story starts in the middle of the action."),
    ("juxtaposition","literature",2,3,3,3,4,"Two things side by side to make the contrast bite."),
    ("meta-narrative","literature",1,1,2,2,4,"A story that knows it is a story."),
    ("onomatopoeia","literature",1,3,2,4,4,"The word sounds like the thing."),
    ("oxymoron","literature",1,2,2,4,4,"Deafening silence. Both words, fighting."),
    ("paradox","literature",1,2,2,4,4,"Contradicts itself, and is somehow true."),
    ("pathetic fallacy","literature",2,3,3,2,4,"The weather matching the mood."),
    ("satire","literature",1,1,2,4,4,"Mockery with a point."),
    ("stream of consciousness","literature",1,2,2,3,4,"Thought written down exactly as it arrives."),
    ("the MacGuffin","literature",2,2,2,2,4,"Everyone chases it. What it is doesn't matter."),
    ("the antihero","literature",1,2,2,4,4,"The protagonist, and not a good person."),
    ("the fourth wall","literature",2,3,3,4,4,"The character turns and looks straight at you."),
    ("the hero's journey","literature",2,3,3,4,3,"Leave home, face the ordeal, return changed."),
    ("tragic flaw","literature",1,2,2,3,4,"The strength that destroys them."),
    ("unreliable narrator","literature",1,2,2,3,4,"The one telling the story is lying to you."),

    # --- maths ---
    ("Bayesian updating","maths",1,1,2,2,4,"New evidence, so you revise how sure you were."),
    ("Godel's incompleteness","maths",1,1,2,2,4,"Some true things can never be proven."),
    ("Klein bottle","maths",3,4,3,2,4,"A bottle whose inside is its outside."),
    ("Monty Hall problem","maths",2,3,3,3,5,"Three doors. Switch. You really should switch."),
    ("brute force","maths",2,3,3,4,4,"Try every possibility until one works."),
    ("chaos theory","maths",1,2,2,4,3,"Tiny differences, wildly different outcomes."),
    ("combinatorial explosion","maths",1,1,2,2,4,"Add one more variable and the options multiply insanely."),
    ("correlation not causation","maths",1,1,2,4,4,"They move together. One did not cause the other."),
    ("exponential growth","maths",2,3,3,4,3,"Doubling, and doubling again, until it's absurd."),
    ("infinity paradox","maths",1,2,2,3,4,"Some infinities are bigger than others."),
    ("margin of error","maths",1,2,2,4,4,"The answer, give or take this much."),
    ("prime number","maths",1,3,2,5,4,"Divisible only by itself and one."),
    ("recursion","maths",2,3,3,4,4,"To understand recursion, first understand recursion."),
    ("regression to the mean","maths",1,1,2,3,4,"An extreme result is usually followed by a normal one."),
    ("sampling bias","maths",1,1,2,3,4,"You asked the wrong people."),
    ("standard deviation","maths",1,2,2,4,4,"How spread out the numbers are."),
    ("statistical significance","maths",1,1,2,4,4,"Unlikely enough to be chance alone."),
    ("the Fibonacci sequence","maths",2,3,3,4,3,"Each number is the two before it, added."),
    ("the birthday paradox","maths",1,1,2,3,4,"Twenty-three people, and two probably share a birthday."),
    ("the halting problem","maths",1,1,2,2,4,"You cannot always know if a program will ever finish."),
    ("the law of large numbers","maths",1,2,2,3,4,"Flip it enough times and it evens out."),
    ("the pigeonhole principle","maths",2,3,3,2,4,"More pigeons than holes. Someone shares."),
    ("the travelling salesman","maths",2,3,3,3,4,"Visit every city once. Find the shortest route. Good luck."),
    ("topology","maths",2,3,3,3,4,"A doughnut and a mug are the same shape."),

    # --- philosophy ---
    ("Chinese room","philosophy",2,3,3,2,4,"Follows the rules perfectly. Understands nothing."),
    ("Fermi paradox","philosophy",1,2,2,2,4,"The universe is vast and silent. Where is everyone?"),
    ("Hanlon's razor","philosophy",1,1,2,2,4,"Never attribute to malice what stupidity explains."),
    ("Occam's broom","philosophy",1,1,2,1,4,"Sweeping the inconvenient facts under the rug."),
    ("Occam's razor","philosophy",1,1,3,3,4,"The simplest explanation usually wins."),
    ("Ockham's simplicity","philosophy",1,1,2,1,4,"Do not multiply entities beyond necessity."),
    ("Pascal's wager","philosophy",1,1,2,2,4,"Believe, because the downside of being wrong is infinite."),
    ("Ship of Theseus","philosophy",2,3,3,2,4,"Replace every plank. Is it still the same ship?"),
    ("Zeno's paradox","philosophy",2,3,3,2,4,"Halfway, then halfway again. You never arrive."),
    ("absurdism","philosophy",1,1,2,2,4,"The search for meaning in a universe that offers none."),
    ("bootstrap paradox","philosophy",1,1,2,2,4,"The thing has no origin. It just loops."),
    ("categorical imperative","philosophy",1,1,2,2,4,"Only act as you'd want everyone to act."),
    ("determinism","philosophy",1,1,2,3,4,"Every choice was already settled."),
    ("dualism","philosophy",1,1,2,2,4,"Mind and body as two separate things."),
    ("epistemology","philosophy",1,1,2,2,4,"The study of how we know what we know."),
    ("existential crisis","philosophy",1,2,2,4,4,"Three in the morning. Why any of this?"),
    ("free will","philosophy",1,2,2,4,4,"Did you choose that, or only feel like you did?"),
    ("grandfather paradox","philosophy",2,3,3,3,4,"Go back, prevent your own birth, and then?"),
    ("moral relativism","philosophy",1,1,2,3,4,"Right and wrong depend on where you're standing."),
    ("nihilism","philosophy",1,1,2,3,4,"Nothing means anything."),
    ("philosophical zombie","philosophy",2,2,2,2,4,"Behaves exactly like you. Experiences nothing."),
    ("reductio ad absurdum","philosophy",1,1,2,2,4,"Follow their logic until it becomes ridiculous."),
    ("solipsism","philosophy",1,1,2,2,4,"Only your own mind is certain to exist."),
    ("stoicism","philosophy",1,1,2,3,4,"Control what you can. Accept the rest."),
    ("tabula rasa","philosophy",1,2,2,2,4,"Born a blank slate."),
    ("the Sorites paradox","philosophy",2,2,2,1,4,"Remove one grain. Still a heap? When does it stop?"),
    ("the golden mean","philosophy",1,2,2,3,4,"Virtue sits between two extremes."),
    ("the golden rule","philosophy",1,2,3,4,4,"Treat others as you'd want treating."),
    ("the hard problem of consciousness","philosophy",1,1,2,2,4,"Why does any of this feel like anything?"),
    ("the is-ought problem","philosophy",1,1,2,1,4,"You can't derive what should be from what is."),
    ("the liar paradox","philosophy",1,2,2,2,4,"'This sentence is false.'"),
    ("the observer's paradox","philosophy",1,1,2,2,4,"Studying it is what changed it."),
    ("the veil of ignorance","philosophy",1,2,2,2,4,"Design society before you know who you'll be in it."),
    ("utilitarianism","philosophy",1,1,2,3,4,"The greatest good for the greatest number."),

    # --- science ---
    ("Heisenberg uncertainty","science",1,1,2,3,4,"Know the speed or the place. Never both."),
    ("Schrodinger's equation","science",1,1,2,2,4,"The maths that predicts where a particle probably is."),
    ("absolute zero","science",1,2,2,4,3,"As cold as cold can possibly get."),
    ("antimatter","science",1,2,2,4,3,"The mirror of matter. They annihilate on contact."),
    ("centrifugal force","science",2,3,3,4,3,"Spin fast enough and everything flings outward."),
    ("cosmic background radiation","science",1,1,2,2,3,"The faint afterglow of the beginning."),
    ("dark matter","science",1,2,2,4,3,"Most of the universe, and nobody can see it."),
    ("entropy","science",1,2,2,4,4,"Everything tends toward disorder."),
    ("escape velocity","science",2,3,3,4,3,"Fast enough to leave and never fall back."),
    ("event horizon","science",2,3,3,3,3,"Cross it and nothing comes back. Not even light."),
    ("gravitational lensing","science",2,3,3,2,3,"Gravity bends light around a heavy thing."),
    ("half-life","science",1,2,2,4,4,"Wait, and half of it is gone. Wait again."),
    ("heat death of the universe","science",1,2,2,2,3,"Everything, eventually, the same temperature."),
    ("nuclear fusion","science",2,3,3,4,3,"Squeeze two atoms into one. Stars do it constantly."),
    ("quantum entanglement","science",1,1,2,2,3,"Two particles. One fate. Any distance."),
    ("redshift","science",2,3,3,3,3,"Moving away, so the light stretches redder."),
    ("relativity","science",1,2,2,4,4,"Time and space bend depending on who's watching."),
    ("resonance","science",2,3,3,3,3,"Push at the right rhythm and it shakes apart."),
    ("spaghettification","science",2,3,3,2,5,"Stretched thin by gravity, feet first."),
    ("string theory","science",1,2,2,3,3,"Everything is vibrating loops, far too small to see."),
    ("supernova","science",2,3,3,4,3,"A star's final, spectacular detonation."),
    ("superposition","science",1,1,2,3,4,"Every state at once, until observed."),
    ("terminal velocity","science",2,3,3,3,3,"Falling, but no longer speeding up."),
    ("the Doppler effect","science",2,3,3,4,4,"The siren's pitch drops as it passes."),
    ("the multiverse","science",1,2,2,4,3,"Every possible outcome, each in its own universe."),
    ("thermal equilibrium","science",1,2,2,3,4,"Everything settles to one temperature."),
    ("tidal locking","science",2,3,3,2,3,"The moon always shows us the same face."),
    ("time dilation","science",1,2,2,3,4,"Move fast enough and your clock runs slow."),
    ("wave-particle duality","science",1,2,2,3,4,"It is both, depending on how you look."),
]
