# Tier: God Mode — score >= 8 AND a specialist domain AND a mandatory meaning
# Specialist domains: biases, philosophy, science, biology, economics, internet, maths, literature
# Gate: T >= 2, meaning required (build fails without one), 1-of-3 playtest gate before shipping.
# Tuple: (text, category, C, F, D, R, T, meaning)

WORDS = [

    # --- biases ---
    ("Barnum effect","biases",1,1,2,2,4,"That horoscope describes literally everyone."),
    ("Dunning-Kruger effect","biases",1,1,2,2,4,"Too inexperienced to know how inexperienced you are."),
    ("anchoring bias","biases",1,1,2,2,4,"The first number you heard is still steering you."),
    ("availability heuristic","biases",1,1,2,2,4,"Easy to recall, so it feels common."),
    ("base rate fallacy","biases",1,1,2,2,4,"You ignored how rare the thing actually is."),
    ("bystander effect","biases",1,2,3,3,4,"A crowd watched. Nobody helped."),
    ("choice paralysis","biases",1,2,2,4,4,"Thirty options, so you picked none."),
    ("cognitive dissonance","biases",1,1,2,3,4,"Two beliefs. One head. They cannot both be right."),
    ("confirmation bias","biases",1,1,2,3,4,"You went looking, and found exactly what you expected."),
    ("curse of knowledge","biases",1,1,2,2,4,"You can't remember what it was like not to know."),
    ("decision fatigue","biases",1,2,2,4,4,"By evening, every choice is a bad one."),
    ("endowment effect","biases",1,1,2,2,4,"It's worth more the moment it becomes yours."),
    ("false consensus","biases",1,1,2,2,4,"Everyone thinks like me. They don't."),
    ("framing effect","biases",1,1,2,3,4,"Ninety percent fat free sells better than ten percent fat."),
    ("fundamental attribution error","biases",1,1,2,2,4,"They're late because they're careless. You're late because of traffic."),
    ("gambler's fallacy","biases",1,1,2,3,4,"It's landed heads five times, so tails is 'due'."),
    ("halo effect","biases",1,2,2,3,4,"They're attractive, so you assume they're clever too."),
    ("illusion of control","biases",1,1,2,3,4,"Pressing the button harder does nothing."),
    ("in-group bias","biases",1,1,2,3,4,"Ours is better because it is ours."),
    ("loss aversion","biases",1,1,2,3,4,"Losing ten hurts more than winning ten feels good."),
    ("moral licensing","biases",1,1,2,2,4,"I ate the salad, so I've earned the cake."),
    ("negativity bias","biases",1,1,2,3,4,"One bad review outweighs nine good ones."),
    ("normalcy bias","biases",1,1,2,2,4,"The alarm is going off. Everyone keeps eating."),
    ("observer effect","biases",1,1,2,3,4,"Watching it changed it."),
    ("optimism bias","biases",1,1,2,3,4,"Bad things happen to other people."),
    ("placebo effect","biases",1,2,2,4,4,"The sugar pill worked anyway."),
    ("planning fallacy","biases",1,1,2,3,4,"It always takes three times longer than you said."),
    ("recency bias","biases",1,1,2,3,4,"The last thing that happened weighs the most."),
    ("self-serving bias","biases",1,1,2,3,4,"Wins are skill. Losses are bad luck."),
    ("spotlight effect","biases",1,1,2,3,4,"Nobody noticed your haircut."),
    ("status quo bias","biases",1,1,2,3,4,"Change is worse simply because it is change."),
    ("sunk cost fallacy","biases",1,1,2,3,4,"You've already paid. That is the worst reason to continue."),
    ("survivorship bias","biases",1,1,2,2,4,"You only counted the planes that came back."),

    # --- biology ---
    ("DNA replication","biology",2,3,3,4,3,"The ladder unzips and copies itself."),
    ("REM sleep","biology",2,3,3,4,4,"Eyes darting. This is where dreams happen."),
    ("antibiotic resistance","biology",1,2,2,4,3,"The survivors breed, and the medicine stops working."),
    ("apoptosis","biology",1,1,2,1,4,"Cells that kill themselves on purpose."),
    ("cellular respiration","biology",1,2,2,3,3,"Turning food into usable energy."),
    ("circadian rhythm","biology",1,2,2,4,4,"The clock you carry whether you like it or not."),
    ("convergent evolution","biology",1,1,2,2,4,"Unrelated species, same solution."),
    ("ecological succession","biology",1,1,2,2,4,"Bare rock, then moss, then forest."),
    ("epigenetics","biology",1,1,2,2,4,"The environment flipping switches on your genes."),
    ("genetic drift","biology",1,1,2,2,4,"Change by pure chance, not fitness."),
    ("herd immunity","biology",1,2,2,5,4,"Enough are protected that the rest are too."),
    ("hibernation cycle","biology",2,3,3,4,3,"Shut down through the cold months."),
    ("homeostasis","biology",1,1,2,3,4,"The body's relentless thermostat."),
    ("imprinting","biology",2,3,3,3,4,"The first thing it sees becomes its mother."),
    ("keystone species","biology",1,2,2,2,4,"Remove it and the whole system collapses."),
    ("mitosis","biology",2,3,3,4,3,"One cell becomes two identical ones."),
    ("muscle atrophy","biology",2,3,3,4,3,"Unused, so it wastes away."),
    ("natural selection","biology",1,2,2,5,3,"The ones that fit, breed. The rest don't."),
    ("neuroplasticity","biology",1,1,2,3,4,"The brain rewiring itself."),
    ("parasitism","biology",2,3,3,4,4,"One benefits. The other pays."),
    ("phantom limb","biology",2,3,3,4,4,"It itches, and it isn't there."),
    ("pheromones","biology",1,1,2,3,4,"Chemical messages you never consciously smell."),
    ("synaptic pruning","biology",1,1,2,2,4,"The brain deleting connections it stopped using."),
    ("the immune response","biology",1,2,2,4,3,"An army that learns its enemy."),
    ("the placebo response","biology",1,1,2,4,4,"Believing it works is what made it work."),

    # --- economics ---
    ("Nash equilibrium","economics",1,1,2,2,4,"Nobody gains by changing strategy alone."),
    ("arbitrage","economics",1,1,2,3,4,"Buy cheap here, sell dear there, risk nothing."),
    ("barrier to entry","economics",2,3,3,4,3,"The wall keeping new competitors out."),
    ("black swan event","economics",2,3,3,3,4,"Unthinkable, until it happens."),
    ("compound growth","economics",1,2,2,4,4,"Slow, slow, slow, then suddenly enormous."),
    ("creative destruction","economics",1,2,2,2,4,"The new industry kills the old one. That's the point."),
    ("diminishing returns","economics",1,1,3,3,3,"Each extra unit buys you less than the last."),
    ("economies of scale","economics",1,2,2,4,3,"Bigger means cheaper per unit."),
    ("first mover advantage","economics",1,2,2,4,4,"Get there first and own the ground."),
    ("game theory","economics",1,1,2,4,4,"Maths for when the other side is also thinking."),
    ("inelastic demand","economics",1,1,2,2,4,"They'll buy it whatever you charge."),
    ("inflation spiral","economics",1,2,2,4,4,"Prices rise, wages chase, prices rise again."),
    ("market saturation","economics",1,2,2,4,4,"Everyone who wants one already has one."),
    ("moral hazard","economics",1,1,2,2,4,"Insured against the risk, so you take more of it."),
    ("network effect","economics",1,2,2,4,3,"Worth more because everyone else is on it."),
    ("opportunity cost","economics",1,1,2,3,4,"What you gave up by choosing this."),
    ("perverse incentive","economics",1,1,2,3,4,"You rewarded it, so they did more of it. Badly."),
    ("planned obsolescence","economics",2,3,3,4,4,"Designed to break just after the warranty."),
    ("price elasticity","economics",1,1,2,3,4,"How much demand flinches when price moves."),
    ("supply shock","economics",1,2,2,3,4,"The supply vanishes overnight, the price explodes."),
    ("the Veblen good","economics",1,1,2,1,4,"Expensive is the feature. Cheaper would sell less."),
    ("the free rider problem","economics",2,3,3,3,4,"Enjoys the benefit, pays none of the cost."),
    ("the invisible hand","economics",2,3,3,3,4,"Self-interest, somehow producing public good."),
    ("the paradox of thrift","economics",1,1,2,2,4,"Everyone saves. Everyone gets poorer."),
    ("the prisoner's dilemma","economics",2,3,3,3,4,"Both stay silent and both win. Neither trusts the other."),
    ("the race to the bottom","economics",2,3,3,3,4,"Everyone undercuts until nobody profits."),
    ("the tragedy of the commons","economics",2,3,3,3,4,"Shared field. Everyone grazes. Nothing left."),
    ("vertical integration","economics",1,2,2,3,3,"Own every step from raw material to shop floor."),
    ("zero sum game","economics",1,2,2,4,4,"For me to win, you must lose exactly that much."),

    # --- internet ---
    ("Betteridge's law","internet",1,1,2,1,4,"Any headline ending in a question mark: the answer is no."),
    ("Godwin's law","internet",1,1,2,2,4,"Argue long enough and someone mentions Hitler."),
    ("Moore's law","internet",1,2,2,4,4,"Chips double in power, roughly every two years."),
    ("Poe's law","internet",1,1,2,2,4,"Satire indistinguishable from sincerity."),
    ("algorithmic bias","internet",1,1,2,3,4,"The machine learned our prejudices and scaled them."),
    ("astroturfing","internet",1,1,2,2,4,"Fake grassroots. Paid for."),
    ("attention economy","internet",1,2,2,3,4,"Your eyes are the product being sold."),
    ("clickbait economy","internet",2,3,3,4,4,"Outrage pays better than accuracy."),
    ("dead internet theory","internet",1,1,2,2,4,"What if most of it is bots talking to bots?"),
    ("digital footprint","internet",2,3,3,4,4,"Everything you did, still there."),
    ("digital minimalism","internet",1,2,2,3,4,"Deliberately owning fewer apps, fewer feeds."),
    ("doomscrolling","internet",2,3,3,4,4,"Can't stop reading things that make you feel worse."),
    ("echo chamber","internet",2,3,3,4,3,"Everyone agrees, because you removed everyone who didn't."),
    ("feature creep","internet",1,2,2,4,4,"It kept growing until nobody could use it."),
    ("filter bubble","internet",2,3,3,3,4,"The algorithm only shows you what you already like."),
    ("network congestion","internet",2,3,3,4,3,"Everyone connected at once, so nobody gets through."),
    ("open source","internet",1,2,2,5,4,"Anyone can read it, change it, and give it back."),
    ("planned virality","internet",1,1,2,2,4,"Engineered to look spontaneous."),
    ("rubber duck debugging","internet",3,4,3,2,4,"Explain the problem to a toy and solve it yourself."),
    ("technical debt","internet",1,2,2,4,4,"Shortcuts today, paid back with interest later."),
    ("the Streisand effect","internet",1,2,3,2,4,"Suppressing it is what made everyone look."),
    ("the bus factor","internet",2,3,3,2,5,"How many people can leave before the project dies."),
    ("the long tail","internet",1,2,2,3,4,"A million niche things outselling the hits combined."),
    ("the uncanny valley","internet",2,3,3,3,4,"Almost human. That's what makes it horrifying."),

    # --- literature ---
    ("Chekhov's gun","literature",2,3,3,3,4,"If it's on the wall in act one, it fires by act three."),
    ("allegory","literature",1,1,2,3,4,"The whole story is secretly about something else."),
    ("bildungsroman","literature",1,1,2,1,4,"A story about growing up."),
    ("catharsis","literature",1,1,2,3,4,"The emotional release the ending gives you."),
    ("deus ex machina","literature",2,3,3,3,4,"A sudden rescue that solves everything. Cheating."),
    ("dramatic irony","literature",1,2,2,3,4,"The audience knows. The character doesn't."),
    ("epistolary","literature",2,3,3,1,4,"The whole novel told in letters."),
    ("foreshadowing","literature",1,2,2,4,4,"A hint of what's coming, planted early."),
    ("hyperbole","literature",1,2,2,4,4,"Absurd exaggeration, for effect."),
    ("in medias res","literature",1,1,2,2,4,"The story starts in the middle of the action."),
    ("juxtaposition","literature",2,3,3,3,4,"Two things side by side to make the contrast bite."),
    ("meta-narrative","literature",1,1,2,2,4,"A story that knows it is a story."),
    ("onomatopoeia","literature",1,3,2,4,4,"The word sounds like the thing."),
    ("oxymoron","literature",1,2,2,4,4,"Deafening silence. Both words, fighting."),
    ("paradox","literature",1,2,2,4,4,"Contradicts itself, and is somehow true."),
    ("pathetic fallacy","literature",2,3,3,2,4,"The weather matching the mood."),
    ("satire","literature",1,1,2,4,4,"Mockery with a point."),
    ("stream of consciousness","literature",1,2,2,3,4,"Thought written down exactly as it arrives."),
    ("the MacGuffin","literature",2,2,2,2,4,"Everyone chases it. What it is doesn't matter."),
    ("the antihero","literature",1,2,2,4,4,"The protagonist, and not a good person."),
    ("the fourth wall","literature",2,3,3,4,4,"The character turns and looks straight at you."),
    ("the hero's journey","literature",2,3,3,4,3,"Leave home, face the ordeal, return changed."),
    ("tragic flaw","literature",1,2,2,3,4,"The strength that destroys them."),
    ("unreliable narrator","literature",1,2,2,3,4,"The one telling the story is lying to you."),

    # --- maths ---
    ("Bayesian updating","maths",1,1,2,2,4,"New evidence, so you revise how sure you were."),
    ("Godel's incompleteness","maths",1,1,2,2,4,"Some true things can never be proven."),
    ("Klein bottle","maths",3,4,3,2,4,"A bottle whose inside is its outside."),
    ("Monty Hall problem","maths",2,3,3,3,5,"Three doors. Switch. You really should switch."),
    ("brute force","maths",2,3,3,4,4,"Try every possibility until one works."),
    ("chaos theory","maths",1,2,2,4,3,"Tiny differences, wildly different outcomes."),
    ("combinatorial explosion","maths",1,1,2,2,4,"Add one more variable and the options multiply insanely."),
    ("correlation not causation","maths",1,1,2,4,4,"They move together. One did not cause the other."),
    ("exponential growth","maths",2,3,3,4,3,"Doubling, and doubling again, until it's absurd."),
    ("infinity paradox","maths",1,2,2,3,4,"Some infinities are bigger than others."),
    ("margin of error","maths",1,2,2,4,4,"The answer, give or take this much."),
    ("prime number","maths",1,3,2,5,4,"Divisible only by itself and one."),
    ("recursion","maths",2,3,3,4,4,"To understand recursion, first understand recursion."),
    ("regression to the mean","maths",1,1,2,3,4,"An extreme result is usually followed by a normal one."),
    ("sampling bias","maths",1,1,2,3,4,"You asked the wrong people."),
    ("standard deviation","maths",1,2,2,4,4,"How spread out the numbers are."),
    ("statistical significance","maths",1,1,2,4,4,"Unlikely enough to be chance alone."),
    ("the Fibonacci sequence","maths",2,3,3,4,3,"Each number is the two before it, added."),
    ("the birthday paradox","maths",1,1,2,3,4,"Twenty-three people, and two probably share a birthday."),
    ("the halting problem","maths",1,1,2,2,4,"You cannot always know if a program will ever finish."),
    ("the law of large numbers","maths",1,2,2,3,4,"Flip it enough times and it evens out."),
    ("the pigeonhole principle","maths",2,3,3,2,4,"More pigeons than holes. Someone shares."),
    ("the travelling salesman","maths",2,3,3,3,4,"Visit every city once. Find the shortest route. Good luck."),
    ("topology","maths",2,3,3,3,4,"A doughnut and a mug are the same shape."),

    # --- philosophy ---
    ("Chinese room","philosophy",2,3,3,2,4,"Follows the rules perfectly. Understands nothing."),
    ("Fermi paradox","philosophy",1,2,2,2,4,"The universe is vast and silent. Where is everyone?"),
    ("Hanlon's razor","philosophy",1,1,2,2,4,"Never attribute to malice what stupidity explains."),
    ("Occam's broom","philosophy",1,1,2,1,4,"Sweeping the inconvenient facts under the rug."),
    ("Occam's razor","philosophy",1,1,3,3,4,"The simplest explanation usually wins."),
    ("Ockham's simplicity","philosophy",1,1,2,1,4,"Do not multiply entities beyond necessity."),
    ("Pascal's wager","philosophy",1,1,2,2,4,"Believe, because the downside of being wrong is infinite."),
    ("Ship of Theseus","philosophy",2,3,3,2,4,"Replace every plank. Is it still the same ship?"),
    ("Zeno's paradox","philosophy",2,3,3,2,4,"Halfway, then halfway again. You never arrive."),
    ("absurdism","philosophy",1,1,2,2,4,"The search for meaning in a universe that offers none."),
    ("bootstrap paradox","philosophy",1,1,2,2,4,"The thing has no origin. It just loops."),
    ("categorical imperative","philosophy",1,1,2,2,4,"Only act as you'd want everyone to act."),
    ("determinism","philosophy",1,1,2,3,4,"Every choice was already settled."),
    ("dualism","philosophy",1,1,2,2,4,"Mind and body as two separate things."),
    ("epistemology","philosophy",1,1,2,2,4,"The study of how we know what we know."),
    ("existential crisis","philosophy",1,2,2,4,4,"Three in the morning. Why any of this?"),
    ("free will","philosophy",1,2,2,4,4,"Did you choose that, or only feel like you did?"),
    ("grandfather paradox","philosophy",2,3,3,3,4,"Go back, prevent your own birth, and then?"),
    ("moral relativism","philosophy",1,1,2,3,4,"Right and wrong depend on where you're standing."),
    ("nihilism","philosophy",1,1,2,3,4,"Nothing means anything."),
    ("philosophical zombie","philosophy",2,2,2,2,4,"Behaves exactly like you. Experiences nothing."),
    ("reductio ad absurdum","philosophy",1,1,2,2,4,"Follow their logic until it becomes ridiculous."),
    ("solipsism","philosophy",1,1,2,2,4,"Only your own mind is certain to exist."),
    ("stoicism","philosophy",1,1,2,3,4,"Control what you can. Accept the rest."),
    ("tabula rasa","philosophy",1,2,2,2,4,"Born a blank slate."),
    ("the Sorites paradox","philosophy",2,2,2,1,4,"Remove one grain. Still a heap? When does it stop?"),
    ("the golden mean","philosophy",1,2,2,3,4,"Virtue sits between two extremes."),
    ("the golden rule","philosophy",1,2,3,4,4,"Treat others as you'd want treating."),
    ("the hard problem of consciousness","philosophy",1,1,2,2,4,"Why does any of this feel like anything?"),
    ("the is-ought problem","philosophy",1,1,2,1,4,"You can't derive what should be from what is."),
    ("the liar paradox","philosophy",1,2,2,2,4,"'This sentence is false.'"),
    ("the observer's paradox","philosophy",1,1,2,2,4,"Studying it is what changed it."),
    ("the veil of ignorance","philosophy",1,2,2,2,4,"Design society before you know who you'll be in it."),
    ("utilitarianism","philosophy",1,1,2,3,4,"The greatest good for the greatest number."),

    # --- science ---
    ("Heisenberg uncertainty","science",1,1,2,3,4,"Know the speed or the place. Never both."),
    ("Schrodinger's equation","science",1,1,2,2,4,"The maths that predicts where a particle probably is."),
    ("absolute zero","science",1,2,2,4,3,"As cold as cold can possibly get."),
    ("antimatter","science",1,2,2,4,3,"The mirror of matter. They annihilate on contact."),
    ("centrifugal force","science",2,3,3,4,3,"Spin fast enough and everything flings outward."),
    ("cosmic background radiation","science",1,1,2,2,3,"The faint afterglow of the beginning."),
    ("dark matter","science",1,2,2,4,3,"Most of the universe, and nobody can see it."),
    ("entropy","science",1,2,2,4,4,"Everything tends toward disorder."),
    ("escape velocity","science",2,3,3,4,3,"Fast enough to leave and never fall back."),
    ("event horizon","science",2,3,3,3,3,"Cross it and nothing comes back. Not even light."),
    ("gravitational lensing","science",2,3,3,2,3,"Gravity bends light around a heavy thing."),
    ("half-life","science",1,2,2,4,4,"Wait, and half of it is gone. Wait again."),
    ("heat death of the universe","science",1,2,2,2,3,"Everything, eventually, the same temperature."),
    ("nuclear fusion","science",2,3,3,4,3,"Squeeze two atoms into one. Stars do it constantly."),
    ("quantum entanglement","science",1,1,2,2,3,"Two particles. One fate. Any distance."),
    ("redshift","science",2,3,3,3,3,"Moving away, so the light stretches redder."),
    ("relativity","science",1,2,2,4,4,"Time and space bend depending on who's watching."),
    ("resonance","science",2,3,3,3,3,"Push at the right rhythm and it shakes apart."),
    ("spaghettification","science",2,3,3,2,5,"Stretched thin by gravity, feet first."),
    ("string theory","science",1,2,2,3,3,"Everything is vibrating loops, far too small to see."),
    ("supernova","science",2,3,3,4,3,"A star's final, spectacular detonation."),
    ("superposition","science",1,1,2,3,4,"Every state at once, until observed."),
    ("terminal velocity","science",2,3,3,3,3,"Falling, but no longer speeding up."),
    ("the Doppler effect","science",2,3,3,4,4,"The siren's pitch drops as it passes."),
    ("the multiverse","science",1,2,2,4,3,"Every possible outcome, each in its own universe."),
    ("thermal equilibrium","science",1,2,2,3,4,"Everything settles to one temperature."),
    ("tidal locking","science",2,3,3,2,3,"The moon always shows us the same face."),
    ("time dilation","science",1,2,2,3,4,"Move fast enough and your clock runs slow."),
    ("wave-particle duality","science",1,2,2,3,4,"It is both, depending on how you look."),
]

# ===========================================================================
# Expansion — corpus 2026.09.2
#
# Gate: score >= 8, a specialist domain, T >= 2, and a MEANING that the word
# screen prints underneath the term, always, for free. That last field changed
# job in Sep 2026: it used to be an optional hint bought with half the round's
# points, and it is now a definition the drawer reads before they start. Write
# it as a definition, not a riddle — "the drawer has to draw the idea, and they
# cannot draw what they cannot define."
#
# God Mode is deliberately the SMALLEST tier and must stay that way. Past roughly
# 1,500 words you are admitting terms that fail the Recognition axis, and a word
# no one in the room has ever heard is not a hard round, it is a lost one.
# ===========================================================================

WORDS += [

    # --- biases ---
    ("actor-observer bias","biases",1,1,2,2,4,"Your own behaviour is explained by circumstance; everyone else's, by character."),
    ("affect heuristic","biases",1,1,2,2,4,"Judging risk by how something makes you feel rather than by the numbers."),
    ("ambiguity effect","biases",1,1,2,2,4,"Avoiding the option whose odds you don't know, even when it is the better bet."),
    ("appeal to authority","biases",1,1,2,3,4,"Treating a claim as true because someone important said it."),
    ("appeal to nature","biases",1,1,2,3,4,"Assuming something is good simply because it is natural."),
    ("attentional bias","biases",1,1,2,2,3,"What you happen to be paying attention to distorts what you conclude."),
    ("automation bias","biases",1,1,2,2,4,"Trusting the machine's answer over your own eyes."),
    ("backfire effect","biases",1,1,2,2,5,"Contradicting evidence makes the belief stronger, not weaker."),
    ("bandwagon effect","biases",1,2,2,3,4,"Adopting a belief because the number of people holding it is growing."),
    ("belief perseverance","biases",1,1,2,2,4,"Keeping a belief after the evidence it rested on has been withdrawn."),
    ("black and white thinking","biases",1,1,2,3,4,"Treating everything as one extreme or the other, with nothing in between."),
    ("bounded rationality","biases",1,1,2,2,3,"Deciding sensibly within the limits of the time and information you actually have."),
    ("cheerleader effect","biases",1,1,2,2,5,"People look more attractive in a group than they do alone."),
    ("clustering illusion","biases",1,1,2,2,4,"Seeing a pattern in what is only a run of random results."),
    ("conjunction fallacy","biases",1,1,2,2,4,"Believing two things together are likelier than either one alone."),
    ("contrast effect","biases",1,1,2,3,4,"Something looks better or worse depending on what you saw just before it."),
    ("Cunningham's law","biases",1,1,2,2,5,"The fastest way to get the right answer online is to post the wrong one."),
    ("declinism","biases",1,1,2,2,4,"The belief that things were better before and are steadily getting worse."),
    ("egocentric bias","biases",1,1,2,2,4,"Remembering your own part in something as larger than it was."),
    ("empathy gap","biases",1,1,2,2,4,"When calm, you cannot predict what you will do when you are not."),
    ("false dilemma","biases",1,1,2,3,4,"Presenting two options as the only two when others exist."),
    ("false memory","biases",1,2,2,3,4,"Recalling, in detail and with confidence, something that never happened."),
    ("frequency illusion","biases",1,1,2,2,5,"You notice it once, and now it seems to be everywhere."),
    ("functional fixedness","biases",1,1,2,2,4,"Only being able to see an object used the way it is usually used."),
    ("Goodhart's law","biases",1,1,2,2,4,"When a measure becomes a target, it stops being a good measure."),
    ("Hawthorne effect","biases",1,1,2,2,4,"People behave differently when they know they are being watched."),
    ("hedonic treadmill","biases",1,1,2,2,4,"However good or bad things get, you drift back to roughly the same mood."),
    ("hot hand fallacy","biases",1,1,2,2,4,"Believing a run of luck makes the next attempt more likely to land."),
    ("hyperbolic discounting","biases",1,1,2,2,4,"Preferring a small reward now to a much larger one later."),
    ("IKEA effect","biases",1,1,2,2,5,"You value the thing more because you assembled it yourself."),
    ("illusory correlation","biases",1,1,2,2,4,"Seeing a link between two things that are not actually connected."),
    ("illusory superiority","biases",1,1,2,2,4,"Almost everyone rates themselves as above average."),
    ("impact bias","biases",1,1,2,2,4,"Overestimating how long and how strongly a future event will affect you."),
    ("just world hypothesis","biases",1,1,2,2,4,"Assuming people get what they deserve, so victims must have earned it."),
    ("law of the instrument","biases",1,1,2,2,5,"If all you have is a hammer, everything starts to look like a nail."),
    ("Lindy effect","biases",1,1,2,2,4,"The longer something has already survived, the longer it is likely to last."),
    ("mere exposure effect","biases",1,1,2,2,4,"You like it more simply because you have seen it before."),
    ("Murphy's law","biases",1,2,2,4,4,"Anything that can go wrong, will."),
    ("naive realism","biases",1,1,2,2,4,"Assuming you see the world as it is, and that dissenters are biased."),
    ("nirvana fallacy","biases",1,1,2,2,4,"Rejecting a workable solution because it is not a perfect one."),
    ("no true Scotsman","biases",1,1,2,2,5,"Redefining the group to exclude any counterexample raised against it."),
    ("omission bias","biases",1,1,2,2,4,"Judging harm caused by doing nothing as less bad than harm caused by acting."),
    ("ostrich effect","biases",1,1,2,2,5,"Avoiding information you expect to be unwelcome."),
    ("outcome bias","biases",1,1,2,2,4,"Judging a decision by how it turned out rather than by how it was made."),
    ("overconfidence effect","biases",1,1,2,3,4,"Your certainty is consistently higher than your accuracy."),
    ("Parkinson's law","biases",1,1,2,2,5,"Work expands to fill the time available for it."),
    ("peak-end rule","biases",1,1,2,2,4,"You remember an experience by its most intense moment and its ending."),
    ("Peter principle","biases",1,1,2,2,5,"People get promoted until they reach a job they are bad at, and stay there."),
    ("pratfall effect","biases",1,1,2,2,5,"A small blunder makes a competent person more likeable."),
    ("present bias","biases",1,1,2,2,4,"Now weighs far more heavily than later."),
    ("primacy effect","biases",1,1,2,2,4,"The first thing in a list is the thing you remember."),
    ("pygmalion effect","biases",1,1,2,2,4,"People perform to the level that is expected of them."),
    ("reactance","biases",1,1,2,2,4,"Wanting something more the moment you are told you cannot have it."),
    ("rosy retrospection","biases",1,1,2,2,4,"The past looks better in memory than it did while you were living it."),
    ("Semmelweis reflex","biases",1,1,2,1,4,"Rejecting new evidence because it contradicts the established view."),
    ("serial position effect","biases",1,1,2,2,4,"You recall the start and the end of a list, and lose the middle."),
    ("shifting baseline","biases",1,1,2,2,4,"Each generation treats the degraded world it inherited as normal."),
    ("social desirability bias","biases",1,1,2,2,4,"Survey answers drift towards whatever sounds respectable."),
    ("special pleading","biases",1,1,2,2,4,"Claiming an exemption from a rule without justifying the exception."),
    ("straw man fallacy","biases",1,1,2,3,4,"Attacking a weakened version of the argument instead of the real one."),
    ("the Cobra effect","biases",1,1,2,2,5,"A reward for solving a problem creates more of the problem."),
    ("the Zeigarnik effect","biases",1,1,2,1,4,"Unfinished tasks stay in your head; finished ones vanish from it."),
    ("third person effect","biases",1,1,2,2,4,"Believing persuasion works on other people but not on you."),
    ("ultimate attribution error","biases",1,1,2,2,4,"Our group's failures are circumstance; theirs are character."),
    ("von Restorff effect","biases",1,1,2,1,4,"The item that stands out from the rest is the one you remember."),
    ("zero risk bias","biases",1,1,2,2,4,"Preferring to eliminate one small risk entirely over cutting a big one in half."),
]

WORDS += [

    # --- philosophy ---
    ("a priori knowledge","philosophy",1,1,2,2,4,"Something you can know without going out and checking."),
    ("aesthetics","philosophy",1,1,2,3,3,"The branch of philosophy that asks what makes a thing beautiful."),
    ("agnosticism","philosophy",1,1,2,4,3,"Holding that the answer is not, and may never be, knowable."),
    ("anthropic principle","philosophy",1,1,2,2,4,"The universe looks fine-tuned for us because otherwise we would not be here to look."),
    ("Buridan's ass","philosophy",1,1,2,1,5,"A donkey exactly between two identical meals starves, unable to choose."),
    ("Cartesian doubt","philosophy",1,1,2,2,4,"Doubting everything you can, to find what cannot be doubted."),
    ("causality","philosophy",1,2,2,4,3,"The relationship between a thing that happens and the thing that made it happen."),
    ("collective unconscious","philosophy",1,1,2,2,4,"A shared layer of imagery and symbols said to be inherited, not learned."),
    ("consequentialism","philosophy",1,1,2,2,3,"An act is right or wrong according to its outcomes, and nothing else."),
    ("cosmological argument","philosophy",1,1,2,2,3,"Everything has a cause, so something uncaused must have started it."),
    ("cynicism","philosophy",1,2,2,4,3,"The belief that people act from self-interest whatever they claim."),
    ("deontology","philosophy",1,1,2,2,3,"Some acts are simply forbidden, whatever good they might produce."),
    ("dialectic","philosophy",1,1,2,2,3,"Truth arrived at by setting an idea against its opposite."),
    ("dystopia","philosophy",1,2,2,4,4,"An imagined society organised so that life in it is terrible."),
    ("empiricism","philosophy",1,1,2,3,3,"All knowledge comes from experience and observation."),
    ("Epicureanism","philosophy",1,1,2,2,3,"A quiet life of modest pleasure and absent pain is the good one."),
    ("essentialism","philosophy",1,1,2,2,3,"Every thing has a fixed set of properties that make it what it is."),
    ("eternal recurrence","philosophy",1,1,2,2,4,"You will live this exact life again, endlessly. Would you accept it?"),
    ("existentialism","philosophy",1,1,2,3,4,"You exist first and make your meaning afterwards; nothing hands it to you."),
    ("falsifiability","philosophy",1,1,2,2,4,"A claim is scientific only if some observation could prove it wrong."),
    ("fatalism","philosophy",1,1,2,3,3,"Whatever you do, the outcome was always going to be that one."),
    ("first cause","philosophy",1,1,2,3,4,"The thing at the start of the chain that nothing else caused."),
    ("Gettier problem","philosophy",1,1,2,1,4,"A belief can be true, and justified, and still not count as knowledge."),
    ("hedonism","philosophy",1,1,2,3,3,"Pleasure is the only thing worth pursuing for its own sake."),
    ("humanism","philosophy",1,1,2,3,3,"Human reason and dignity, rather than the divine, as the measure of things."),
    ("infinite regress","philosophy",1,1,2,2,4,"Each answer needs another answer behind it, forever."),
    ("logical positivism","philosophy",1,1,2,1,3,"If a statement cannot be verified, it is not false — it is meaningless."),
    ("magical realism","philosophy",1,1,2,3,4,"An ordinary world in which one impossible thing is treated as unremarkable."),
    ("materialism","philosophy",1,1,2,3,3,"Everything that exists is physical, mind included."),
    ("metaphysics","philosophy",1,1,2,3,3,"The study of what fundamentally exists, beneath the things you can measure."),
    ("Molyneux's problem","philosophy",1,1,2,1,4,"Someone blind from birth, suddenly seeing: could they tell a cube from a sphere?"),
    ("monism","philosophy",1,1,2,1,3,"Everything is ultimately one substance, not two."),
    ("Newcomb's problem","philosophy",1,1,2,1,4,"Take both boxes, or one? A perfect predictor has already guessed your choice."),
    ("ontology","philosophy",1,1,2,2,3,"The study of what kinds of things exist at all."),
    ("panpsychism","philosophy",1,1,2,1,4,"The view that consciousness is a basic feature of all matter."),
    ("Pascal's mugging","philosophy",1,1,2,1,5,"A tiny chance of an enormous payoff can hijack any rational calculation."),
    ("phenomenology","philosophy",1,1,2,2,3,"Studying experience from the inside, as it is actually lived."),
    ("qualia","philosophy",1,1,2,2,4,"The raw feel of an experience — what red is actually like to you."),
    ("rationalism","philosophy",1,1,2,3,3,"Reason, not the senses, is the reliable route to knowledge."),
    ("Schopenhauer's porcupines","philosophy",1,1,2,1,5,"Too close and they prick each other; too far and they freeze."),
    ("simulation hypothesis","philosophy",1,1,2,3,4,"The proposition that all of this is a computation running somewhere else."),
    ("Socratic method","philosophy",1,1,2,3,4,"Teaching by asking questions until the other person finds the answer."),
    ("teleology","philosophy",1,1,2,1,3,"Explaining a thing by the purpose it serves rather than the cause behind it."),
    ("the Euthyphro dilemma","philosophy",1,1,2,1,4,"Is it good because it is commanded, or commanded because it is good?"),
    ("the Munchhausen trilemma","philosophy",1,1,2,1,4,"Every proof rests on circularity, infinite regress, or an unproven starting point."),
    ("the experience machine","philosophy",1,1,2,2,4,"Plug in for a lifetime of perfect simulated happiness. Would you?"),
    ("the mind-body problem","philosophy",1,1,2,3,4,"How can something physical produce something that feels like anything?"),
    ("the paradox of tolerance","philosophy",1,1,2,2,4,"Unlimited tolerance eventually destroys the tolerant."),
    ("the problem of evil","philosophy",1,1,2,3,4,"If a good and all-powerful god exists, why is there suffering?"),
    ("the problem of induction","philosophy",1,1,2,2,4,"The sun rose every day so far. That is not proof it rises tomorrow."),
    ("the ring of Gyges","philosophy",1,1,2,1,5,"If you could not be caught, would you still behave well?"),
    ("transcendentalism","philosophy",1,1,2,2,3,"Truth is found through intuition and nature rather than doctrine."),
    ("utopia","philosophy",1,2,2,4,4,"An imagined society arranged so that everything in it works."),
    ("virtue ethics","philosophy",1,1,2,2,3,"Ask what a good person would do, rather than which rule applies."),
    ("Wittgenstein's beetle","philosophy",1,1,2,1,5,"Everyone has a box nobody else can look into. What does the word even refer to?"),

    # --- science ---
    ("Brownian motion","science",1,2,2,2,3,"The jittering of tiny particles knocked about by the molecules around them."),
    ("Coriolis effect","science",1,2,2,3,4,"The planet's spin bends the path of anything moving across it."),
    ("Faraday cage","science",2,3,3,3,4,"A metal shell that keeps electric fields out of what is inside it."),
    ("Hubble constant","science",1,1,2,2,3,"The number describing how fast the universe is expanding."),
    ("Kessler syndrome","science",1,1,2,2,4,"One collision in orbit makes debris that causes the next, and the next."),
    ("Lagrange point","science",1,1,2,2,3,"A spot where two bodies' gravity lets a third one sit still."),
    ("Maxwell's demon","science",1,1,2,2,5,"An imaginary doorman who sorts fast molecules from slow ones and seems to beat physics."),
    ("Newton's cradle","science",2,3,3,4,4,"The desk toy: one ball swings in, one swings out, momentum passed along the row."),
    ("Ohm's law","science",1,2,2,3,3,"Voltage equals current times resistance."),
    ("Planck length","science",1,1,2,2,3,"The smallest distance at which the idea of distance still means anything."),
    ("Rayleigh scattering","science",1,1,2,2,4,"Air scatters blue light most, which is why the sky is blue."),
    ("accretion disc","science",1,2,2,2,3,"The flattened, glowing ring of matter spiralling into something massive."),
    ("albedo","science",1,1,2,2,3,"How much of the light falling on a surface it reflects back."),
    ("angular momentum","science",1,2,2,3,3,"The spin a rotating thing keeps unless something twists it."),
    ("big crunch","science",1,2,2,2,4,"The universe stops expanding and collapses back in on itself."),
    ("binary star","science",2,3,3,3,3,"Two stars orbiting a shared centre of gravity."),
    ("blueshift","science",2,3,3,3,3,"Light squeezed bluer because its source is coming towards you."),
    ("capillary action","science",2,3,3,3,3,"Liquid climbing a narrow tube without being pushed."),
    ("catalysis","science",1,2,2,3,3,"Speeding up a reaction with something that is not consumed by it."),
    ("centripetal force","science",1,2,2,3,3,"The inward pull that keeps something moving in a circle."),
    ("conservation of energy","science",1,2,2,3,3,"Energy is never created or destroyed, only moved and changed."),
    ("convection","science",1,2,2,3,3,"Heat carried by a fluid rising as it warms and sinking as it cools."),
    ("cryogenics","science",1,2,2,3,3,"The physics of temperatures close to absolute zero."),
    ("dark energy","science",1,1,2,3,4,"The unexplained something pushing the universe apart faster and faster."),
    ("diffraction","science",1,2,2,3,3,"Waves bending around an edge and spreading out behind it."),
    ("electromagnetism","science",1,2,2,3,3,"Electricity and magnetism as two faces of one force."),
    ("exoplanet","science",1,2,2,3,3,"A planet orbiting a star that is not the Sun."),
    ("gamma ray burst","science",1,1,2,2,4,"The most violent explosion known, visible across the entire universe."),
    ("gravitational waves","science",1,1,2,3,4,"Ripples in space itself, made when very heavy things collide."),
    ("Higgs boson","science",1,1,2,3,4,"The particle tied to the field that gives other particles their mass."),
    ("interference pattern","science",1,2,2,2,4,"Overlapping waves adding up in some places and cancelling in others."),
    ("isotope","science",1,2,2,3,3,"Same element, different number of neutrons."),
    ("kinetic energy","science",1,2,2,4,3,"The energy a thing has because it is moving."),
    ("laminar flow","science",1,2,2,2,3,"Fluid moving in smooth parallel layers, with no mixing between them."),
    ("latent heat","science",1,1,2,2,3,"The energy a substance takes in to change state without changing temperature."),
    ("light year","science",1,2,2,4,4,"A distance, not a time: how far light travels in a year."),
    ("magnetic field","science",2,3,3,4,3,"The region around a magnet where it can pull or push."),
    ("mass-energy equivalence","science",1,1,2,3,4,"Mass and energy are the same thing in different clothes."),
    ("microgravity","science",1,2,2,3,3,"The near-weightlessness of orbit, where everything is falling together."),
    ("neutron star","science",1,2,2,3,4,"A collapsed star so dense a teaspoon of it would weigh millions of tonnes."),
    ("nucleosynthesis","science",1,1,2,1,4,"Stars building heavier elements out of lighter ones."),
    ("parallax","science",1,2,2,2,3,"A near object appears to shift against the background when you move."),
    ("particle accelerator","science",1,2,2,3,3,"A machine that flings particles at each other to see what falls out."),
    ("phase transition","science",1,2,2,3,3,"Matter switching state — ice to water, water to steam."),
    ("photon","science",1,2,2,3,3,"A single particle of light."),
    ("plasma state","science",1,2,2,3,3,"The fourth state of matter: gas hot enough that its electrons come loose."),
    ("potential energy","science",1,2,2,4,3,"Stored energy, waiting on position — the boulder at the top of the hill."),
    ("quantum tunnelling","science",1,1,2,2,4,"A particle passing through a barrier it should not have the energy to cross."),
    ("quasar","science",1,2,2,3,3,"A young galaxy's core, blazing as its black hole feeds."),
    ("radioactivity","science",1,2,2,4,3,"An unstable nucleus shedding particles until it settles."),
    ("refraction","science",2,3,3,4,3,"Light bending as it passes from one material into another."),
    ("solar wind","science",1,2,2,3,3,"A constant stream of charged particles blowing off the Sun."),
    ("sonic boom","science",2,3,3,4,4,"The crack heard when something outruns its own sound."),
    ("spectroscopy","science",1,1,2,2,3,"Reading what a thing is made of from the light it gives off."),
    ("standard model","science",1,1,2,2,3,"Physics' catalogue of the known particles and the forces between them."),
    ("stellar nursery","science",1,2,2,2,4,"A cloud of gas and dust in which new stars are forming."),
    ("sublimation","science",1,2,2,2,4,"Solid straight to gas, skipping liquid entirely."),
    ("superconductivity","science",1,1,2,3,4,"At low enough temperatures, resistance disappears completely."),
    ("surface tension","science",2,3,3,4,4,"The skin on water that lets an insect stand on it."),
    ("thermodynamics","science",1,1,2,3,3,"The physics of heat, work and what energy will and will not do."),
    ("torque","science",1,2,2,3,3,"Twisting force — what a spanner applies to a bolt."),
    ("viscosity","science",1,2,2,4,3,"How reluctantly a fluid flows. Honey has a lot of it."),
    ("wavelength","science",1,2,2,4,3,"The distance from one wave crest to the next."),
    ("white dwarf","science",1,2,2,3,3,"The dense, cooling ember a star like the Sun leaves behind."),
]

WORDS += [

    # --- biology ---
    ("adaptive radiation","biology",1,1,2,2,3,"One ancestor species fanning out into many, each suited to a different niche."),
    ("amino acid","biology",1,2,2,3,3,"The building block proteins are assembled from."),
    ("antigen","biology",1,1,2,3,3,"Anything the immune system recognises as foreign and reacts to."),
    ("binary fission","biology",1,2,2,2,3,"One cell splitting cleanly into two — how bacteria reproduce."),
    ("biodiversity","biology",1,2,2,4,3,"The variety of living things in a place."),
    ("biome","biology",1,2,2,3,3,"A large habitat type — desert, tundra, rainforest — with its own community."),
    ("carrying capacity","biology",1,1,2,2,3,"The largest population an environment can support without degrading."),
    ("cell membrane","biology",2,3,3,4,3,"The gatekeeper wall around a cell, letting some things in and not others."),
    ("chlorophyll","biology",1,2,2,4,3,"The green pigment plants use to catch light."),
    ("chloroplast","biology",1,2,2,3,3,"The part of a plant cell where photosynthesis actually happens."),
    ("cloning","biology",1,2,2,4,4,"Producing an organism genetically identical to another."),
    ("commensalism","biology",1,1,2,2,3,"One species benefits; the other is neither helped nor harmed."),
    ("cytoplasm","biology",1,2,2,3,3,"The jelly inside a cell that everything else sits in."),
    ("decomposer","biology",2,3,3,4,3,"The organisms that break the dead back down into soil."),
    ("dominant gene","biology",1,2,2,4,3,"The version of a gene that shows up even when only one copy is present."),
    ("double helix","biology",2,3,3,4,4,"DNA's shape: two strands twisted around each other like a spiral ladder."),
    ("ecological niche","biology",1,1,2,2,3,"The exact role and set of conditions a species occupies."),
    ("endosymbiosis","biology",1,1,2,1,4,"One cell swallowed another and kept it. That is where mitochondria came from."),
    ("enzyme","biology",1,2,2,4,3,"A protein that speeds up one specific reaction in the body."),
    ("eukaryote","biology",1,1,2,2,3,"A cell with a nucleus — plants, animals, fungi, you."),
    ("extremophile","biology",1,1,2,2,4,"An organism that thrives where nothing should: boiling vents, acid, ice."),
    ("gene expression","biology",1,1,2,3,3,"A gene being switched on and actually used to build something."),
    ("gene pool","biology",1,1,2,3,3,"All the genetic variation available in a population."),
    ("germ theory","biology",1,2,2,4,3,"Disease is caused by microorganisms, not bad air."),
    ("gestation","biology",1,2,2,4,3,"The period of carrying young before birth."),
    ("gut microbiome","biology",1,2,2,3,3,"The community of microbes living in your digestive tract."),
    ("haemoglobin","biology",1,2,2,3,3,"The molecule in blood that carries oxygen and makes it red."),
    ("heredity","biology",1,2,2,4,3,"The passing of traits from parents to offspring."),
    ("hybrid vigour","biology",1,1,2,2,4,"Crossing two lines producing offspring stronger than either parent."),
    ("hydroponics","biology",2,3,3,3,3,"Growing plants in nutrient water, with no soil at all."),
    ("incubation period","biology",1,2,2,3,3,"The gap between catching something and showing any sign of it."),
    ("larval stage","biology",2,3,3,4,3,"The young form that looks nothing like the adult it becomes."),
    ("meiosis","biology",1,2,2,3,3,"The cell division that makes egg and sperm cells, halving the chromosomes."),
    ("metabolism","biology",1,2,2,4,3,"All the chemistry that keeps a body running."),
    ("mitochondria","biology",1,2,2,4,4,"The parts of a cell that turn fuel into usable energy."),
    ("mutation","biology",1,2,2,4,3,"A change in the genetic code, copied onwards from there."),
    ("mutualism","biology",1,1,2,3,3,"Two species in an arrangement that benefits them both."),
    ("nitrogen cycle","biology",1,1,2,3,3,"Nitrogen moving between air, soil, plants and animals and back."),
    ("organelle","biology",1,2,2,2,3,"A specialised structure inside a cell, like an organ in miniature."),
    ("osmosis","biology",1,2,2,4,3,"Water moving through a membrane towards the saltier side."),
    ("pathogen","biology",1,2,2,4,3,"An organism that causes disease."),
    ("phylogeny","biology",1,1,2,1,3,"The family tree showing how species descend from common ancestors."),
    ("plankton bloom","biology",2,3,3,3,3,"A sudden explosion of microscopic life colouring the water."),
    ("predator prey cycle","biology",1,2,2,3,4,"Predator numbers rise, prey crash, predators crash, prey recover. Repeat."),
    ("prokaryote","biology",1,1,2,2,3,"A cell with no nucleus — bacteria, and the oldest life there is."),
    ("protein folding","biology",1,1,2,2,4,"A chain of amino acids collapsing into the exact shape that makes it work."),
    ("recessive gene","biology",1,2,2,4,3,"The version of a gene that only shows when both copies carry it."),
    ("ribosome","biology",1,2,2,2,3,"The cell's assembly line, reading instructions and building proteins."),
    ("speciation","biology",1,1,2,3,3,"One population splitting into two that can no longer interbreed."),
    ("stem cell","biology",1,2,2,4,4,"A cell that has not decided yet what kind of cell to become."),
    ("taxonomy","biology",1,1,2,3,3,"The system for naming living things and sorting them into groups."),
    ("thermoregulation","biology",1,1,2,3,3,"Keeping body temperature steady whatever the weather is doing."),
    ("transpiration","biology",1,2,2,2,3,"Water pulled up a plant and released as vapour from its leaves."),
    ("trophic cascade","biology",1,1,2,2,4,"Removing a top predator changes everything down the food chain."),
    ("vestigial organ","biology",1,2,2,3,4,"A leftover body part that no longer does the job it evolved for."),
    ("viral load","biology",1,1,2,3,3,"How much virus is present in a body at one time."),
    ("zoonosis","biology",1,1,2,2,4,"A disease that jumps from animals to humans."),

    # --- economics ---
    ("adverse selection","economics",1,1,2,2,4,"The people most eager to buy insurance are the ones most likely to claim."),
    ("aggregate demand","economics",1,1,2,3,2,"Everything an economy wants to buy, added together."),
    ("asymmetric information","economics",1,1,2,2,4,"One side of the deal knows more than the other."),
    ("bank run","economics",2,3,3,3,4,"Everyone withdraws at once because everyone fears everyone will."),
    ("bear market","economics",1,2,2,4,4,"A long slide in prices, and the pessimism that comes with it."),
    ("behavioural economics","economics",1,1,2,3,3,"Economics that assumes people are human rather than perfectly rational."),
    ("bull market","economics",1,2,2,4,4,"A long climb in prices, and the confidence that comes with it."),
    ("capital flight","economics",1,1,2,2,4,"Money leaving a country fast because it no longer trusts it."),
    ("cartel","economics",1,2,2,3,4,"Rivals agreeing to fix prices instead of competing on them."),
    ("circular economy","economics",1,2,2,3,3,"Designing so that waste becomes the next thing's raw material."),
    ("comparative advantage","economics",1,1,2,2,4,"Each side should do what it gives up least to produce."),
    ("consumer surplus","economics",1,1,2,2,3,"The gap between what you would have paid and what you did pay."),
    ("deadweight loss","economics",1,1,2,1,3,"Value that simply vanishes because a market was distorted."),
    ("deflation","economics",1,2,2,3,3,"Prices falling — which sounds good, and stalls an economy."),
    ("demand curve","economics",1,2,2,3,2,"The line showing how much people buy at each price."),
    ("dumping","economics",1,1,2,2,4,"Selling abroad below cost to push local competitors out."),
    ("efficient market hypothesis","economics",1,1,2,2,3,"Prices already contain everything that is known, so nobody can beat them."),
    ("externality","economics",1,1,2,2,4,"A cost or benefit landing on someone who was not part of the deal."),
    ("fiat currency","economics",1,1,2,3,4,"Money that is worth something only because everyone agrees it is."),
    ("fiscal policy","economics",1,1,2,3,2,"Government steering the economy through spending and taxation."),
    ("gig economy","economics",1,2,2,4,3,"Work sold job by job rather than by the salaried month."),
    ("Giffen good","economics",1,1,2,1,5,"A staple people buy MORE of as it gets more expensive."),
    ("gross domestic product","economics",1,1,2,4,3,"The total value of everything a country produces in a year."),
    ("import tariff","economics",1,2,2,3,3,"A tax on goods coming in, to make local ones look cheaper."),
    ("index fund","economics",1,1,2,3,3,"A fund that buys the whole market instead of trying to pick winners."),
    ("informal economy","economics",1,1,2,3,3,"Real work and real trade that no official ledger records."),
    ("Jevons paradox","economics",1,1,2,1,5,"Making something more efficient can make total consumption go up."),
    ("laissez-faire","economics",1,1,2,3,3,"Leave the market alone and let it sort itself out."),
    ("law of demand","economics",1,2,2,4,2,"Raise the price and, all else equal, people buy less."),
    ("liquidity trap","economics",1,1,2,2,3,"Rates are at the floor and cheap money still will not move anyone."),
    ("marginal utility","economics",1,1,2,2,4,"The second slice is good. The eighth is not."),
    ("market failure","economics",1,1,2,3,3,"When a free market produces an outcome that is worse for everyone."),
    ("monetary policy","economics",1,1,2,3,2,"A central bank steering the economy through interest rates and money supply."),
    ("oligopoly","economics",1,1,2,3,3,"A market run by a handful of firms who all watch each other."),
    ("price ceiling","economics",1,2,2,3,3,"A legal maximum price, which tends to produce a shortage."),
    ("price floor","economics",1,2,2,3,3,"A legal minimum price, which tends to produce a surplus."),
    ("principal agent problem","economics",1,1,2,2,4,"You hired someone to act for you, and their interests are not yours."),
    ("public good","economics",1,1,2,3,3,"Something nobody can be excluded from and using it does not use it up."),
    ("quantitative easing","economics",1,1,2,3,3,"A central bank creating money to buy assets and push it into the economy."),
    ("rent seeking","economics",1,1,2,2,4,"Getting richer by capturing a bigger share rather than making anything."),
    ("reserve currency","economics",1,1,2,2,3,"The money other countries hold because everyone else accepts it."),
    ("stagflation","economics",1,1,2,2,4,"Prices rising and the economy shrinking at the same time."),
    ("subsidy","economics",1,2,2,4,3,"Public money paid in to hold a price down or keep a producer going."),
    ("supply curve","economics",1,2,2,3,2,"The line showing how much producers will make at each price."),
    ("switching cost","economics",1,1,2,3,4,"What it costs you to leave, which is why you have not."),
    ("the Laffer curve","economics",1,1,2,2,4,"Tax at zero raises nothing, and so does tax at a hundred percent."),
    ("the Lipstick index","economics",1,1,2,1,5,"In a downturn, people stop buying big things and buy small treats instead."),
    ("the Phillips curve","economics",1,1,2,1,3,"The claimed trade-off between unemployment and inflation."),
    ("the multiplier effect","economics",1,1,2,2,4,"One pound spent becomes someone's income, and they spend it too."),
    ("the wealth effect","economics",1,1,2,2,3,"People spend more when their assets look more valuable on paper."),
    ("trade deficit","economics",1,2,2,3,3,"Importing more than you export."),
    ("trickle down","economics",1,1,2,3,4,"The claim that gains at the top eventually reach the bottom."),
    ("velocity of money","economics",1,1,2,2,3,"How often the same unit of currency changes hands in a year."),
    ("winner's curse","economics",1,1,2,2,5,"Win the auction and you have probably overpaid — that is why you won."),
]

WORDS += [

    # --- internet ---
    ("A/B testing","internet",1,2,2,3,3,"Show half the users one version, half the other, and keep the winner."),
    ("attention residue","internet",1,1,2,2,4,"Part of your mind stays on the last task after you have switched."),
    ("backdoor","internet",1,2,2,4,4,"A deliberate way in that bypasses the front door entirely."),
    ("big data","internet",1,2,2,4,3,"Data too large and messy for ordinary tools to handle."),
    ("cache","internet",1,2,2,4,3,"A local copy kept close by so you do not have to fetch it again."),
    ("click through rate","internet",1,2,2,3,3,"The share of people who saw it and actually clicked."),
    ("cloud computing","internet",1,2,2,4,3,"Renting someone else's computers instead of owning your own."),
    ("content moderation","internet",1,2,2,4,3,"Deciding what a platform will and will not carry."),
    ("context collapse","internet",1,1,2,2,4,"One post reaching every audience you have at once, with no separation."),
    ("dark pattern","internet",1,1,2,3,5,"An interface designed to trick you into the choice it wants."),
    ("data mining","internet",1,2,2,4,3,"Digging through large data for patterns nobody put there on purpose."),
    ("deepfake","internet",1,2,2,4,4,"Synthetic video or audio of a real person doing what they never did."),
    ("dependency hell","internet",1,1,2,2,4,"Everything needs a different version of the same thing."),
    ("digital divide","internet",1,1,2,3,3,"The gap between those with reliable access and those without."),
    ("dogfooding","internet",1,1,2,2,5,"Making the team use the product they build, every day."),
    ("edge case","internet",1,1,2,4,3,"The rare input at the boundary that breaks the whole thing."),
    ("encryption","internet",1,2,2,4,3,"Scrambling data so only the holder of the key can read it."),
    ("engagement bait","internet",1,2,2,3,4,"Content written to provoke a reaction rather than to say anything."),
    ("enshittification","internet",1,1,2,2,5,"A platform gets worse for users to get better for shareholders."),
    ("feature flag","internet",1,1,2,2,3,"A switch that turns a feature on for some people and not others."),
    ("fingerprinting","internet",1,1,2,3,4,"Identifying a browser by its quirks, with no cookie needed."),
    ("flame war","internet",1,2,2,4,4,"An argument online that has stopped being about anything."),
    ("freemium","internet",1,2,2,4,3,"Free until the part you actually wanted."),
    ("garbage in garbage out","internet",1,2,2,4,4,"Bad input guarantees bad output, however good the system is."),
    ("generative model","internet",1,1,2,4,3,"A system trained to produce new text, images or sound."),
    ("graceful degradation","internet",1,1,2,2,3,"When part of it fails, the rest keeps working instead of collapsing."),
    ("hallucination","internet",1,1,2,4,5,"A model stating something invented with complete confidence."),
    ("hash function","internet",1,1,2,2,3,"Turning any input into a fixed-length fingerprint you cannot reverse."),
    ("heisenbug","internet",1,1,2,1,5,"A bug that disappears the moment you try to observe it."),
    ("honeypot","internet",1,2,2,3,4,"A deliberately tempting trap left out to catch intruders."),
    ("infinite scroll","internet",1,2,2,4,4,"A feed with no bottom, so there is never a moment to stop."),
    ("information cascade","internet",1,1,2,2,4,"Everyone copies the person in front, and nobody checks the original."),
    ("internet of things","internet",1,2,2,4,3,"Ordinary objects put online, whether or not that was wise."),
    ("latency","internet",1,2,2,4,3,"The delay between asking and getting an answer."),
    ("load balancing","internet",1,2,2,3,3,"Spreading traffic across several machines so none of them falls over."),
    ("machine learning","internet",1,2,2,4,3,"Software that improves from examples rather than from written rules."),
    ("man in the middle","internet",1,2,2,3,4,"Someone sitting quietly between two parties, reading everything."),
    ("metadata","internet",1,1,2,4,4,"Data about the data — who, when and from where, if not what."),
    ("microtransaction","internet",1,2,2,4,3,"A small purchase inside a product you already paid for."),
    ("network topology","internet",1,2,2,2,3,"The shape of how machines are wired together."),
    ("overfitting","internet",1,1,2,2,4,"A model that memorised the practice questions and fails the real exam."),
    ("packet loss","internet",1,2,2,3,3,"Some of the data never arrives, and the call stutters."),
    ("parasocial relationship","internet",1,1,2,3,4,"You know everything about them; they have never heard of you."),
    ("phishing","internet",1,2,2,4,4,"A fake message designed to get you to hand over your details."),
    ("platform lock-in","internet",1,1,2,3,4,"Leaving would cost you everything you have already put in."),
    ("privacy paradox","internet",1,1,2,2,4,"People say they care about privacy and trade it away for almost nothing."),
    ("proof of work","internet",1,1,2,3,3,"Proving you did the computation by making it expensive to fake."),
    ("race condition","internet",1,1,2,2,4,"Two things happen at once and the result depends on which won."),
    ("rate limiting","internet",1,2,2,3,3,"Capping how often one caller may ask."),
    ("recommendation engine","internet",1,2,2,4,3,"The system deciding what you see next."),
    ("root access","internet",1,2,2,3,4,"Permission to do absolutely anything on the machine."),
    ("sandboxing","internet",1,2,2,3,4,"Running something inside a box so it cannot touch anything else."),
    ("search engine optimisation","internet",1,1,2,4,3,"Shaping a page so a search engine ranks it higher."),
    ("shadow ban","internet",1,1,2,3,5,"You are still posting. Nobody is being shown it."),
    ("single point of failure","internet",1,2,2,4,4,"The one part whose failure takes down everything else."),
    ("social graph","internet",1,2,2,3,3,"The map of who is connected to whom."),
    ("spaghetti code","internet",1,2,2,3,5,"Code so tangled that no thread can be pulled without moving the rest."),
    ("surveillance capitalism","internet",1,1,2,3,4,"A business model built on recording behaviour and selling predictions of it."),
    ("throttling","internet",1,2,2,3,3,"Deliberately slowing something down rather than stopping it."),
    ("vaporware","internet",1,1,2,2,5,"Announced, promoted, and never actually shipped."),
    ("version control","internet",1,2,2,4,3,"A record of every change, and a way back to any of them."),
    ("web crawler","internet",1,2,2,3,3,"A program that walks the web, following links and indexing pages."),
    ("yak shaving","internet",1,1,2,1,5,"Six unrelated tasks deep, still not doing the thing you sat down to do."),
    ("zero day","internet",1,1,2,3,4,"A flaw being exploited before anyone has had a day to fix it."),

    # --- literature ---
    ("alter ego","literature",1,2,2,4,4,"A second self, with a different name and a different life."),
    ("anachronism","literature",1,2,2,3,4,"A thing in the wrong century — a wristwatch in ancient Rome."),
    ("anagnorisis","literature",1,1,2,1,4,"The moment the character finally understands what has been true all along."),
    ("antagonist","literature",1,2,2,4,3,"The character standing in the way of what the hero wants."),
    ("archetype","literature",1,1,2,3,3,"A character pattern old enough that everyone recognises it instantly."),
    ("assonance","literature",1,1,2,2,3,"Repeated vowel sounds inside nearby words."),
    ("ballad","literature",1,2,2,4,3,"A poem or song that tells a story, usually in verses."),
    ("bathos","literature",1,1,2,1,5,"A sudden drop from the lofty to the ridiculous."),
    ("blank verse","literature",1,1,2,2,3,"Poetry with a strict rhythm and no rhyme."),
    ("caesura","literature",1,1,2,1,3,"A deliberate pause cut into the middle of a line."),
    ("chiasmus","literature",1,1,2,1,4,"Say it, then say it back to front: ask not what your country can do for you."),
    ("comedy of errors","literature",1,2,2,3,4,"A plot built entirely from people misunderstanding each other."),
    ("couplet","literature",1,2,2,3,3,"Two lines that rhyme and sit together."),
    ("denouement","literature",1,1,2,2,3,"The unwinding after the climax, where everything is settled."),
    ("diction","literature",1,1,2,3,2,"The particular choice of words a writer makes."),
    ("elegy","literature",1,1,2,3,3,"A poem written in mourning."),
    ("enjambment","literature",1,1,2,1,4,"A sentence running past the end of the line without stopping."),
    ("epigraph","literature",1,1,2,2,3,"The quotation printed at the front, before anything begins."),
    ("epiphany","literature",1,1,2,4,4,"A sudden, ordinary moment in which everything becomes clear."),
    ("epithet","literature",1,1,2,2,3,"A descriptive tag welded to a name — swift-footed Achilles."),
    ("eucatastrophe","literature",1,1,2,1,5,"The sudden turn where all is lost and then, impossibly, is not."),
    ("farce","literature",1,2,2,4,4,"Comedy of doors, mistaken identity and escalating chaos."),
    ("flash fiction","literature",1,2,2,3,3,"A complete story told in a page or less."),
    ("foil character","literature",1,1,2,3,4,"A character who exists to make another one's qualities visible by contrast."),
    ("free verse","literature",1,2,2,3,3,"Poetry with no fixed metre or rhyme scheme."),
    ("gothic novel","literature",1,2,2,4,4,"Ruined houses, weather, dread and a secret in the cellar."),
    ("hamartia","literature",1,1,2,1,4,"The error or flaw that brings the hero down."),
    ("iambic pentameter","literature",1,2,2,3,4,"Ten syllables a line, stressed on every second one. Shakespeare's default."),
    ("imagery","literature",1,2,2,4,2,"Writing that puts a picture in the reader's head."),
    ("interior monologue","literature",1,1,2,3,3,"The character's own thoughts, written out as they run."),
    ("kenning","literature",1,1,2,1,5,"An Old Norse riddle-compound: whale-road for the sea."),
    ("leitmotif","literature",1,1,2,2,4,"A recurring phrase or theme tied to one character or idea."),
    ("melodrama","literature",1,2,2,4,4,"Emotions turned all the way up, past what the situation warrants."),
    ("metre","literature",1,1,2,3,3,"The rhythmic pattern a line of poetry is built on."),
    ("monologue","literature",1,2,2,4,3,"One character speaking at length, alone."),
    ("motif","literature",1,1,2,3,3,"An image or idea that keeps returning through a work."),
    ("novella","literature",1,2,2,4,3,"Longer than a short story, shorter than a novel."),
    ("ode","literature",1,2,2,4,3,"A poem written in praise of something."),
    ("omniscient narrator","literature",1,1,2,3,4,"A voice that knows every character's thoughts, including the ones they hide."),
    ("parable","literature",1,2,2,4,3,"A short story told to make a moral point."),
    ("pastiche","literature",1,1,2,2,4,"A work made deliberately in the style of another."),
    ("pathos","literature",1,1,2,3,3,"Writing built to make the reader feel pity."),
    ("picaresque","literature",1,1,2,1,4,"A rogue drifting through episodes, never much changed by any of them."),
    ("polemic","literature",1,1,2,3,3,"A piece written to attack a position, not to weigh it."),
    ("prose poem","literature",1,1,2,2,3,"Poetry written in paragraphs rather than lines."),
    ("purple prose","literature",1,1,2,2,5,"Writing so ornate it stops carrying meaning."),
    ("quatrain","literature",1,1,2,2,3,"A verse of four lines."),
    ("refrain","literature",1,2,2,4,3,"The line that comes back at the end of every verse."),
    ("roman a clef","literature",1,1,2,1,4,"A novel about real people, thinly renamed."),
    ("stanza","literature",1,2,2,4,3,"A block of lines in a poem, set off from the next."),
    ("synaesthesia","literature",1,1,2,3,5,"Describing one sense in the language of another — a loud shirt, a blue note."),
    ("theme","literature",1,1,2,4,2,"What the work is actually about, underneath what happens."),
    ("tragicomedy","literature",1,2,2,3,4,"A story that refuses to settle on being funny or being sad."),
    ("trope","literature",1,1,2,4,4,"A device used so often it arrives pre-recognised."),
    ("verisimilitude","literature",1,1,2,2,3,"The quality of feeling true, whether or not it is."),
    ("vignette","literature",1,1,2,3,3,"A short scene that captures a moment rather than telling a story."),
    ("villanelle","literature",1,1,2,1,4,"A nineteen-line poem built on two lines that keep coming back."),
    ("zeugma","literature",1,1,2,1,5,"One verb doing two jobs: she took her coat and her leave."),

    # --- maths ---
    ("Banach-Tarski paradox","maths",1,1,2,1,5,"Cut a ball apart and reassemble the pieces into two identical balls."),
    ("Bayes' theorem","maths",1,1,2,3,4,"The rule for updating how likely something is once new evidence arrives."),
    ("Benford's law","maths",1,1,2,1,5,"In real-world numbers, the first digit is a 1 far more often than a 9."),
    ("Cantor's diagonal","maths",1,1,2,1,4,"The proof that some infinities are strictly larger than others."),
    ("Collatz conjecture","maths",1,1,2,1,4,"Halve it if even, triple and add one if odd. Everyone lands on 1. Nobody knows why."),
    ("Euler's identity","maths",1,1,2,2,4,"An equation tying together five of the most important numbers in maths."),
    ("Fermat's last theorem","maths",1,1,2,2,4,"A claim scribbled in a margin that took 358 years to prove."),
    ("Fourier transform","maths",1,1,2,2,3,"Breaking any signal down into the pure waves it is made of."),
    ("Goldbach conjecture","maths",1,1,2,1,4,"Every even number seems to be two primes added. Still unproven."),
    ("Hilbert's hotel","maths",1,1,2,1,5,"A hotel with infinite rooms, all full, that can still take another guest."),
    ("Markov chain","maths",1,1,2,2,3,"A process where the next step depends only on where you are now."),
    ("P versus NP","maths",1,1,2,2,4,"If an answer is quick to check, must it also be quick to find?"),
    ("Pascal's triangle","maths",2,3,3,3,4,"A triangle of numbers where each is the sum of the two above it."),
    ("Pythagoras theorem","maths",2,3,3,4,3,"In a right triangle, the two short sides squared add up to the long one squared."),
    ("Riemann hypothesis","maths",1,1,2,2,4,"The most famous unsolved problem in maths, about how primes are spaced."),
    ("Simpson's paradox","maths",1,1,2,1,5,"A trend appears in every group and reverses when the groups are combined."),
    ("Zipf's law","maths",1,1,2,1,4,"The second most common word appears half as often as the first, and so on down."),
    ("asymptote","maths",1,2,2,3,4,"A line a curve gets forever closer to and never touches."),
    ("axiom","maths",1,1,2,3,3,"A starting assumption taken as true without proof."),
    ("big O notation","maths",1,1,2,2,3,"Shorthand for how badly something slows down as the input grows."),
    ("binary code","maths",2,3,3,4,3,"Everything written with only two symbols, 0 and 1."),
    ("calculus","maths",1,2,2,4,3,"The mathematics of change and of accumulation."),
    ("cardinality","maths",1,1,2,2,3,"How many elements a set has — including when the answer is infinite."),
    ("central limit theorem","maths",1,1,2,2,4,"Average enough random things and the result is a bell curve."),
    ("combinatorics","maths",1,1,2,2,3,"The mathematics of counting arrangements and possibilities."),
    ("conditional probability","maths",1,1,2,3,3,"The chance of one thing given that another has already happened."),
    ("confidence interval","maths",1,1,2,3,3,"The range the true answer probably sits in."),
    ("convergence","maths",1,1,2,3,3,"A sequence settling towards a single value."),
    ("cryptography","maths",1,2,2,4,3,"The maths of keeping a message readable only to its recipient."),
    ("derivative","maths",1,1,2,3,3,"The rate at which something is changing, right now."),
    ("differential equation","maths",1,1,2,2,3,"An equation about how a quantity changes rather than what it is."),
    ("eigenvector","maths",1,1,2,1,4,"A direction a transformation stretches but does not turn."),
    ("factorial","maths",1,2,2,3,3,"Multiply every whole number up to it. Five factorial is 120."),
    ("fixed point","maths",1,1,2,2,4,"A value the function leaves exactly where it found it."),
    ("game of life","maths",2,3,3,2,5,"A grid of cells with four rules that produces endless complexity."),
    ("geometric series","maths",1,1,2,2,3,"Each term a fixed multiple of the last — and it can still add to a finite number."),
    ("golden spiral","maths",2,3,3,3,4,"A spiral that widens by the golden ratio every quarter turn."),
    ("graph theory","maths",1,1,2,3,3,"The maths of dots and the lines connecting them."),
    ("greedy algorithm","maths",1,1,2,2,4,"Always take the best-looking step now and hope it works out."),
    ("group theory","maths",1,1,2,2,3,"The mathematics of symmetry, written as rules about operations."),
    ("imaginary number","maths",1,2,2,4,4,"The square root of minus one, and everything built on it."),
    ("information entropy","maths",1,1,2,2,4,"How much surprise a message carries."),
    ("integral","maths",1,1,2,3,3,"The total accumulated — the area under the curve."),
    ("irrational number","maths",1,2,2,4,3,"A number whose decimals never end and never repeat."),
    ("isomorphism","maths",1,1,2,1,4,"Two things with different names and exactly the same structure."),
    ("knot theory","maths",2,3,3,2,4,"The mathematics of which tangles can be undone without cutting."),
    ("lambda calculus","maths",1,1,2,1,3,"A way of describing all computation using only functions."),
    ("law of averages","maths",1,1,2,4,4,"The mistaken belief that chance keeps a running tally and settles up."),
    ("limit","maths",1,1,2,4,3,"The value something approaches as you get arbitrarily close."),
    ("linear regression","maths",1,2,2,3,3,"Drawing the straight line that fits a scatter of points best."),
    ("logarithm","maths",1,2,2,4,3,"The answer to: what power do I raise this to, to get that?"),
    ("modular arithmetic","maths",1,1,2,2,4,"Arithmetic that wraps around, the way a clock does at twelve."),
    ("monte carlo method","maths",1,1,2,2,4,"Solve it by running the random experiment thousands of times."),
    ("non-euclidean geometry","maths",1,1,2,2,4,"Geometry on a curved surface, where parallel lines can meet."),
    ("null hypothesis","maths",1,1,2,3,3,"The boring assumption that nothing is going on, until data says otherwise."),
    ("number theory","maths",1,1,2,3,3,"The study of whole numbers and their stubborn properties."),
    ("orders of magnitude","maths",1,1,2,3,3,"Steps of ten — the difference between a hundred and a million."),
    ("permutation","maths",1,2,2,3,3,"One particular ordering of a set of things."),
    ("polynomial","maths",1,2,2,3,2,"An expression of powers added together, like x squared plus three x."),
    ("power law","maths",1,1,2,2,4,"A few enormous cases and a very long tail of tiny ones."),
    ("prime factorisation","maths",1,2,2,3,3,"Breaking a number into the primes that multiply to make it."),
    ("proof by contradiction","maths",1,1,2,3,4,"Assume the opposite, follow it until it breaks, conclude you were right."),
    ("quadratic formula","maths",1,2,2,4,3,"The one everyone memorised for solving x squared equations."),
    ("random walk","maths",1,2,2,3,4,"Each step chosen at random, with no memory of the last."),
    ("set theory","maths",1,1,2,3,3,"The maths of collections, and of what belongs to what."),
    ("sieve of Eratosthenes","maths",1,2,2,2,4,"Cross out every multiple, and what survives is the primes."),
    ("significant figures","maths",1,1,2,4,3,"How many digits of an answer you are actually entitled to claim."),
    ("stochastic process","maths",1,1,2,2,3,"Something that evolves with randomness built into every step."),
    ("vector space","maths",1,1,2,2,3,"A set of things you can add together and scale up or down."),
    ("weighted average","maths",1,2,2,4,2,"An average where some values are allowed to count for more."),
]
