# Tier: Expert ("Enigma") — score >= 8, CULTURAL-REFERENCE register, mandatory meaning
# Sits between Cryptic and God Mode. Cryptic words are everyday abstractions the
# room names on the first good drawing; God Mode words are specialist terms most
# of a room has never met. Enigma words are NAMED references — myths, eponyms,
# famous effects, history, stories — that most of a room has heard of but has to
# work to reach. Recognition is high (mostly R=4), the drawing path is indirect.
# Categories: myths, eponyms, effects, history, culture  (see BRIDGE in build_corpus.py)
# Gate: T >= 2, meaning required (8-120 chars), same as God Mode.
# Tuple: (text, category, C, F, D, R, T, meaning)

WORDS = [

    # --- myths ---
    ("Kumbhakarna's sleep",'myths',2,2,3,4,4,'Sleeping for months and waking up starving.'),
    ("Abhimanyu's chakravyuh",'myths',2,2,3,3,4,'Knowing how to get in, but not how to get out.'),
    ("Medusa's stare",'myths',2,2,3,3,4,'A look so cold it turns people to stone.'),
    ('the Oracle of Delphi','myths',1,2,3,3,4,'The all-knowing source everyone goes to for answers.'),
    ("Noah's flood",'myths',2,2,3,4,4,'A disaster so total only the prepared survive.'),
    ('Garden of Eden','myths',2,2,3,5,4,'Paradise, right up until the temptation.'),
    ('Narcissus','myths',2,2,3,3,4,'Fell in love with his own reflection.'),
    ('Hydra','myths',2,2,3,3,4,'Cut off one head and two more grow back.'),
    ('Tower of Babel','myths',2,2,3,3,4,'Everyone suddenly speaks a different language, and nothing gets built.'),
    ('wisdom of Solomon','myths',1,2,3,3,4,'Judgement so wise it settles an unsolvable dispute.'),
    ('patience of Job','myths',1,1,3,3,4,'Enduring endless trouble without complaining.'),
    ("Pandora's box","myths",2,2,3,4,4,"Opened out of curiosity, and every trouble in the world got out."),
    ("Achilles' heel","myths",2,2,3,4,4,"The one weak spot in something otherwise unbeatable."),
    ("Midas touch","myths",2,2,3,4,4,"Everything they handle turns to gold."),
    ("Herculean task","myths",1,2,3,4,4,"A job so enormous only a demigod could finish it."),
    ("Sisyphean task","myths",1,2,3,3,4,"Push the boulder up the hill. It rolls back down. Forever."),
    ("flying too close to the sun","myths",2,2,3,4,4,"Ambition that overreaches and ends in a fall."),
    ("Cassandra","myths",1,1,3,3,4,"Right about the coming disaster, and nobody believes her."),
    ("sword of Damocles","myths",2,2,3,3,4,"Danger hanging over you by a single thread."),
    ("Gordian knot","myths",2,2,3,3,4,"An impossible tangle, solved by simply cutting through it."),
    ("odyssey","myths",1,2,3,4,4,"A long, wandering journey full of adventures."),
    ("nemesis","myths",1,2,3,4,4,"The one rival you can never quite shake off."),
    ("siren song","myths",2,2,3,4,4,"A tempting call that lures you towards ruin."),
    ("rising from the ashes","myths",2,2,3,4,4,"Coming back stronger after being completely destroyed."),
    ("El Dorado","myths",1,2,3,3,4,"A legendary city of gold that nobody ever finds."),
    ("Shangri-La","myths",1,2,3,3,4,"A hidden paradise, far away from the rest of the world."),
    ("Atlantis","myths",2,2,3,4,4,"A great city that sank beneath the sea and was lost."),
    ("fountain of youth","myths",2,2,3,4,4,"The magic secret to never growing old."),
    ("Bermuda Triangle","myths",2,2,3,4,4,"Where ships and planes vanish without a trace."),
    ("Area 51","myths",1,2,3,4,4,"The secret base where the aliens are supposedly kept."),
    ("carrying the world on your shoulders","myths",2,2,3,4,4,"Bearing every burden alone, like the Titan Atlas."),

    # --- eponyms ---
    ('Sherlock-level deduction','eponyms',1,2,3,4,4,'Solving it from tiny clues nobody else noticed.'),
    ('Einstein moment','eponyms',1,2,3,4,4,"A flash of genius from someone you didn't expect."),
    ("Chanakya's strategy",'eponyms',1,1,3,3,4,'Cold, clever statecraft that plays the long game.'),
    ('Gandhigiri','eponyms',1,2,3,3,4,'Winning people over with polite, stubborn non-violence.'),
    ('Robin Hood','eponyms',2,2,3,5,4,'Stealing from the rich to give to the poor.'),
    ("Newton's apple",'eponyms',2,2,3,4,4,'The falling apple that explained gravity.'),
    ('Nostradamus','eponyms',1,2,3,3,4,'A vague prophecy that seems to fit anything, afterwards.'),
    ('Mata Hari','eponyms',1,2,3,3,4,'The glamorous spy who seduces secrets out of people.'),
    ("Pavlov's dog","eponyms",2,2,3,4,4,"Ring the bell and the mouth starts watering."),
    ("Stockholm syndrome","eponyms",1,1,3,4,4,"Coming to sympathise with the people holding you captive."),
    ("Peter Pan syndrome","eponyms",1,2,3,4,4,"A grown-up who refuses to grow up."),
    ("Napoleon complex","eponyms",2,2,3,4,4,"Small in height, big on bossing everyone around."),
    ("Machiavellian","eponyms",1,1,2,3,4,"Ruthless cunning used to win and keep power."),
    ("Kafkaesque","eponyms",1,1,2,3,4,"Nightmarishly absurd, pointless bureaucracy."),
    ("Orwellian","eponyms",1,1,2,3,4,"Constant surveillance and lies dressed up as truth."),
    ("Faustian bargain","eponyms",1,1,3,3,4,"Selling your soul for what you want right now."),
    ("Casanova","eponyms",1,2,3,4,4,"A charming serial seducer."),
    ("Scrooge","eponyms",2,2,3,4,4,"Miserly and mean with money, especially at Christmas."),
    ("pulling a Houdini","eponyms",2,2,3,4,4,"Escaping from an impossible situation."),
    ("Rorschach test","eponyms",2,2,3,3,4,"Ink blots that show what's on your mind."),
    ("Mozart effect","eponyms",1,1,2,3,3,"The claim that classical music makes babies smarter."),
    ("tilting at windmills","eponyms",2,2,3,3,4,"Fighting imaginary enemies, like Don Quixote."),
    ("Good Samaritan","eponyms",1,2,3,4,4,"A stranger who stops to help someone in trouble."),
    ("Doubting Thomas","eponyms",1,2,3,4,4,"Won't believe it until they see it for themselves."),
    ("Judas kiss","eponyms",2,2,3,3,4,"Betrayal disguised as affection."),
    ("prodigal son","eponyms",1,2,3,4,4,"Left home, wasted everything, came back and was forgiven."),
    ("Renaissance man","eponyms",1,2,3,4,4,"Brilliant at a bit of everything."),
    ("Jekyll and Hyde","eponyms",2,2,3,4,4,"Two completely different personalities in one person."),
    ("Frankenstein's monster","eponyms",2,2,3,4,4,"A creation that turns on the person who made it."),
    ("Pied Piper","eponyms",2,2,3,4,4,"Someone whose charm makes a crowd follow blindly."),
    ("Big Brother","eponyms",1,2,3,4,4,"The all-seeing authority that is always watching you."),

    # --- effects ---
    ('Monday morning feeling','effects',2,2,3,5,4,'The dread that arrives with the start of the week.'),
    ('the sugar crash','effects',2,2,3,4,4,'The slump that follows the sweet high.'),
    ("beginner's panic",'effects',1,2,3,4,4,'Freezing up the first time it really counts.'),
    ('five-second rule','effects',2,2,3,5,4,"Dropped food is still fine to eat if you're quick."),
    ('rule of three','effects',1,1,3,4,4,'Things feel complete when they come in threes.'),
    ('Friday the 13th','effects',2,2,3,5,4,'The unluckiest date on the calendar.'),
    ('seven-year itch','effects',1,2,3,4,4,'Restlessness that sets in after years together.'),
    ("runner's high",'effects',2,2,3,4,4,'The euphoric buzz that arrives in the middle of a run.'),
    ('terrible twos','effects',2,2,3,4,4,'The tantrum-filled stage every toddler goes through.'),
    ('empty nest syndrome','effects',1,2,3,4,4,'The quiet house after the children move out.'),
    ('middle child syndrome','effects',1,2,3,4,4,"Feeling overlooked when you're neither the eldest nor the baby."),
    ("survival of the fittest","effects",1,2,3,5,4,"Only the best adapted make it through."),
    ("fight or flight","effects",2,2,3,5,4,"Stand your ground or run, decided in a heartbeat."),
    ("photographic memory","effects",2,2,3,4,4,"Remembering everything you've ever seen, exactly."),
    ("self-fulfilling prophecy","effects",1,1,3,4,4,"Believing it will happen is what makes it happen."),
    ("Goldilocks zone","effects",2,2,3,4,4,"Not too hot, not too cold, just right."),
    ("law of attraction","effects",1,1,3,4,4,"Think about it hard enough and it will come to you."),
    ("boiling frog","effects",2,2,3,4,4,"Change so slow you don't notice until it's too late."),
    ("the 80/20 rule","effects",1,1,2,4,4,"Most of the results come from a small slice of the effort."),
    ("10,000 hour rule","effects",1,1,3,4,4,"Practise long enough and you become an expert."),
    ("six degrees of separation","effects",1,2,3,4,4,"Everyone is only a few friends away from everyone else."),
    ("fifteen minutes of fame","effects",1,2,3,5,4,"Famous for a moment, then forgotten."),
    ("mind over matter","effects",1,2,3,5,4,"Willpower beating the body's limits."),
    ("nature versus nurture","effects",1,1,3,4,4,"Were you born this way, or raised this way?"),
    ("underdog effect","effects",1,2,3,4,4,"Everyone roots for the one expected to lose."),
    ("hive mind","effects",2,2,3,4,4,"A crowd thinking and acting as one."),
    ("brainwashing","effects",2,2,3,5,4,"Beliefs installed in your head by someone else."),
    ("survival instinct","effects",1,2,3,5,4,"The urge that kicks in when your life is on the line."),
    ("beginner's mind","effects",1,1,3,3,3,"Approaching something as if for the very first time."),
    ("Eureka moment","effects",1,2,3,5,4,"The sudden flash when the answer finally arrives."),

    # --- history ---
    ('Taj Mahal of love','history',2,2,3,3,4,'A grand monument built out of devotion.'),
    ('burning the boats','history',2,2,3,3,4,'Removing every way back so retreat is impossible.'),
    ('the shot heard round the world','history',1,1,3,3,4,'The first move that starts something enormous.'),
    ('Nero fiddling while Rome burns','history',2,2,3,3,4,'Doing something trivial while everything falls apart.'),
    ('D-Day','history',1,2,3,4,4,'The day the big, long-planned operation finally begins.'),
    ('the Space Race','history',2,2,3,5,4,'Two superpowers racing to reach the Moon first.'),
    ('fall of the Berlin Wall','history',2,2,3,4,4,'The day a divided city became one again.'),
    ('one small step for man','history',2,2,3,4,4,'A tiny action that is a giant leap for everyone.'),
    ('I have a dream','history',1,2,3,4,4,'A vision of a fairer future, spoken out loud.'),
    ("Pyrrhic victory","history",1,1,3,3,4,"Won the battle, but lost so much it barely counts."),
    ("crossing the Rubicon","history",1,2,3,3,4,"Taking the step there is no coming back from."),
    ("meeting your Waterloo","history",1,2,3,3,4,"The final, decisive defeat."),
    ("cold war","history",1,2,3,5,4,"Enemies who never fight each other directly."),
    ("iron curtain","history",2,2,3,4,4,"A hard line that splits the world in two."),
    ("Industrial Revolution","history",2,2,3,5,4,"When machines took over the work of hands."),
    ("Silk Road","history",2,2,3,4,4,"The ancient trade route linking East and West."),
    ("the Enlightenment","history",1,1,2,3,3,"When reason began challenging kings and priests."),
    ("Magna Carta","history",1,1,2,3,3,"The document that said even the king must obey the law."),
    ("let them eat cake","history",2,2,3,4,4,"Out-of-touch advice from someone who has plenty."),
    ("veni vidi vici","history",1,2,3,3,4,"I came, I saw, I conquered."),
    ("Et tu, Brute","history",1,2,3,4,4,"Betrayed by your closest friend."),
    ("divide and rule","history",1,2,3,4,4,"Keep your enemies busy fighting each other."),
    ("Boston Tea Party","history",2,2,3,3,4,"Tea dumped in a harbour to protest a tax."),
    ("Salt March","history",2,2,3,3,4,"Walking to the sea to make salt in defiance of an unfair tax."),
    ("rearranging deckchairs on the Titanic","history",2,2,3,3,4,"Busy, pointless work while disaster approaches."),
    ("Y2K bug","history",1,2,2,4,4,"The fear that every computer would break at midnight in 2000."),
    ("civil disobedience","history",1,2,3,4,4,"Peacefully breaking unfair laws, on purpose."),
    ("the Olympic spirit","history",1,2,3,4,4,"It's the taking part that counts."),
    ("Renaissance","history",1,2,3,5,4,"A sudden rebirth of art and ideas."),
    ("Stone Age thinking","history",2,2,3,4,4,"Hopelessly primitive, out-of-date ideas."),

    # --- culture ---
    ('the Grinch','culture',2,2,3,4,4,"Someone determined to ruin everyone's celebration."),
    ('Mr Bean moment','culture',2,2,3,4,4,'A clumsy, wordless disaster in public.'),
    ("Snow White's mirror",'culture',2,2,3,4,4,"The brutally honest answer you didn't want to hear."),
    ("Pinocchio's nose",'culture',2,2,3,4,4,"The giveaway that proves you're lying."),
    ('Mowgli','culture',2,2,3,4,4,'A child raised by the jungle, wild and free.'),
    ('the Tortoise wins','culture',1,2,3,4,4,'Slow and steady beats fast and careless.'),
    ('Mogambo khush hua','culture',1,2,3,4,4,'The villain is very pleased, and so is everyone else.'),
    ('the elephant and the blind men','culture',2,2,3,3,4,"Everyone holds one piece and thinks it's the whole truth."),
    ('David and Goliath','culture',2,2,3,5,4,'The little one takes down the giant.'),
    ('Cheshire cat grin','culture',2,2,3,4,4,"A wide, knowing grin that lingers after you've gone."),
    ('the wizard behind the curtain','culture',2,2,3,4,4,'The unimpressive person really pulling the strings.'),
    ("there's no place like home",'culture',2,2,3,5,4,'Nowhere beats the place where you belong.'),
    ('the dark side','culture',1,2,3,5,4,'The tempting path that leads to evil.'),
    ("I'll be back",'culture',1,2,3,5,4,'A promise to return that sounds like a threat.'),
    ('Houston, we have a problem','culture',2,2,3,4,4,'Calmly reporting that something has gone badly wrong.'),
    ('Rip Van Winkle','culture',2,2,3,3,4,'Fell asleep for twenty years and woke to a changed world.'),
    ('thought police','culture',1,2,3,4,4,'People who punish you for thinking the wrong thing.'),
    ('Robinson Crusoe','culture',2,2,3,4,4,'Stranded alone on an island, surviving on your wits.'),
    ('chasing a white whale','culture',2,2,3,3,4,'An obsessive pursuit of one elusive goal.'),
    ("emperor's new clothes","culture",2,2,3,4,4,"Everyone pretends to see what simply isn't there."),
    ("the boy who cried wolf","culture",2,2,3,5,4,"Lie often enough and nobody believes the truth."),
    ("killing the golden goose","culture",2,2,3,4,4,"Destroying the very thing that keeps making you money."),
    ("down the rabbit hole","culture",2,2,3,4,4,"One question leads you deeper and deeper in."),
    ("taking the red pill","culture",2,2,3,4,4,"Choosing an uncomfortable truth over a comfortable lie."),
    ("kryptonite","culture",2,2,3,4,4,"The one thing that brings down even the strongest."),
    ("star-crossed lovers","culture",2,2,3,4,4,"Lovers doomed by forces beyond their control."),
    ("Cinderella story","culture",2,2,3,5,4,"From nobody to champion, almost overnight."),
    ("Waiting for Godot","culture",1,1,2,3,4,"Waiting for something that never, ever arrives."),
    ("Lord of the Flies","culture",2,2,3,3,4,"Children left alone turn savage."),
    ("Shakespearean tragedy","culture",1,2,3,4,4,"Everyone dies, and all of it was avoidable."),
    ("Oscar-worthy performance","culture",2,2,3,5,4,"Faking it far too dramatically."),
    ("an offer you can't refuse","culture",1,2,3,4,4,"A deal that is really a threat."),
    ("may the force be with you","culture",2,2,3,4,3,"Good luck, from a galaxy far, far away."),
    ("with great power comes great responsibility","culture",1,1,3,4,4,"The stronger you are, the more you owe everyone else."),
    ("elementary, my dear Watson","culture",1,2,3,4,4,"Said when the answer is obvious, if you'd only noticed."),
    ("the one that got away","culture",2,2,3,5,4,"The chance, or person, you still wish you'd kept."),
    ("happily ever after","culture",1,2,3,5,4,"The fairy-tale ending where nothing goes wrong again."),
]
